#!/usr/bin/env python3
"""Independent arithmetic replay for the frozen Campaign I UC traces.

This verifier deliberately contains its complete interval implementation in this
single file.  It consumes the frozen launch, result, lock, and one-byte DFS
trace as data, but imports no campaign Python module.  All transcendental
arithmetic is performed by python-flint's Arb implementation.  Derivatives of
the displayed Phi functional are generated by the :class:`AD` interval type
below rather than by a second copy of the campaign's expanded formulas.

The independence boundary has two unavoidable limitations which are recorded
in every report: the replay trusts the same trace partition and the same Arb
primitive library as the campaign.  Lambda values are authenticated inputs
from the pinned launch; how they were numerically discovered is immaterial,
because every nonnegative lambda gives a sound feasible-set relaxation.
"""

from __future__ import annotations

import argparse
import datetime as _datetime
from collections import Counter
from fractions import Fraction
import functools
import importlib.metadata as importlib_metadata
import hashlib
import hmac
import json
import math
import os
from pathlib import Path, PurePosixPath
import platform
import re
import stat
import sys
import tempfile
import time

from flint import arb, ctx


NATIVE_PREC_BITS = 160
REPLAY_PREC_BITS = 80
GLOBAL_COVER_CELLS = 20_000
DEFAULT_FACE_MIN_WIDTH = 0.001
DEFAULT_FACE_BOX_BUDGET = 100_000
CHECKPOINT_INTERVAL = 1_000_000

ALPHA_TEXT = "0.0356069"
PINNED_TARGET = "0.3820660112501052"
PINNED_TARGET_UPPER = Fraction(115472366449356389981023, 2**78)
PINNED_CENTER_LAMBDAS = ("0.0", "1.3682158100251758")
Q2_PIN = Fraction(15, 16)

EVENT_MEAN_INFEASIBLE = 0
EVENT_CORNER_INFEASIBLE = 1
EVENT_CORNER = 2
EVENT_RATIO = 3
EVENT_CENTER = 4
EVENT_CENTER_MIXED = 5
EVENT_CENTER_MIXED_SWAP = 6
EVENT_CENTER_W = 7
EVENT_FACE = 8
EVENT_RESIDUAL = 9
EVENT_SPLIT_BASE = 16

EVENT_NAMES = {
    EVENT_MEAN_INFEASIBLE: "infeasible",
    EVENT_CORNER_INFEASIBLE: "infeasible",
    EVENT_CORNER: "corner",
    EVENT_RATIO: "ratio",
    EVENT_CENTER: "center",
    EVENT_CENTER_MIXED: "center_mixed",
    EVENT_CENTER_MIXED_SWAP: "center_mixed_swap",
    EVENT_CENTER_W: "center_w",
    EVENT_FACE: "face",
    EVENT_RESIDUAL: "residual",
    **{EVENT_SPLIT_BASE + coordinate: "split" for coordinate in range(5)},
}
TALLY_NAMES = (
    "processed",
    "infeasible",
    "corner",
    "ratio",
    "center",
    "center_mixed",
    "center_mixed_swap",
    "center_w",
    "face",
    "residual",
    "split",
)

ctx.prec = NATIVE_PREC_BITS
ZERO = arb(0)
ONE = arb(1)
TWO = arb(2)
HALF = ONE / TWO
ALPHA = arb(ALPHA_TEXT)
LOG2 = TWO.log()
BETA = ONE - ALPHA

_RH_GLOBAL_CAP = None
_RHO_GLOBAL_CAP = None
_DQ_ENDPOINT_CAP = None
_ACTIVE_EVENT_CONTEXT = None


class VerificationError(RuntimeError):
    """A fail-closed rejection of an input, trace event, or proof claim."""


# ---------------------------------------------------------------------------
# Exact decimal geometry
# ---------------------------------------------------------------------------

def _fraction_from_exact_arb(value):
    point = arb(value)
    if not point.is_exact():
        raise VerificationError("expected an exact Arb point")
    mantissa, exponent = point.man_exp()
    mantissa, exponent = int(mantissa), int(exponent)
    if exponent >= 0:
        return Fraction(mantissa) * (2**exponent)
    return Fraction(mantissa, 2 ** (-exponent))


def _decimal_fraction(value):
    if isinstance(value, bool):
        raise VerificationError("boolean is not a numeric endpoint")
    if isinstance(value, Fraction):
        return value
    if isinstance(value, int):
        return Fraction(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise VerificationError("non-finite numeric endpoint")
        return Fraction(repr(value))
    if isinstance(value, arb):
        return _fraction_from_exact_arb(value)
    try:
        return Fraction(str(value))
    except (ValueError, TypeError, ZeroDivisionError) as exc:
        raise VerificationError("invalid exact numeric endpoint") from exc


def next_decimal_up(value):
    """Least nearby float whose shortest decimal denotes at least ``value``."""
    target = _decimal_fraction(value)
    candidate = float(target)
    if not math.isfinite(candidate):
        raise VerificationError("decimal cutoff does not fit in a finite float")
    while Fraction(repr(candidate)) < target:
        candidate = math.nextafter(candidate, math.inf)
    return candidate


def _next_decimal_down(value):
    target = _decimal_fraction(value)
    candidate = float(target)
    if not math.isfinite(candidate):
        raise VerificationError("decimal cutoff does not fit in a finite float")
    while Fraction(repr(candidate)) > target:
        candidate = math.nextafter(candidate, -math.inf)
    return candidate


def target_upper_fraction(t_decimal):
    """Return the exact 80-bit Arb upper endpoint used by Campaign I geometry."""
    text = str(t_decimal)
    try:
        rational = Fraction(text)
    except (ValueError, TypeError, ZeroDivisionError) as exc:
        raise VerificationError("target must be a finite decimal rational") from exc
    if rational < 0 or rational > 1:
        raise VerificationError("target must lie in [0,1]")
    previous = ctx.prec
    try:
        ctx.prec = REPLAY_PREC_BITS
        target = arb(text)
        if not target.is_finite():
            raise VerificationError("target did not produce a finite Arb ball")
        return _fraction_from_exact_arb(target.upper())
    finally:
        ctx.prec = previous


def contract_mean(box, t_upper):
    """Contract the weight using exact decimal/Fraction arithmetic.

    A trace endpoint is interpreted as the rational denoted by its shortest
    decimal representation.  ``t_upper`` must be the permissive 80-bit Arb
    upper endpoint, not the exact target decimal; this distinction fixes the
    DFS geometry of the frozen trace.
    """
    coordinates = tuple(box)
    if len(coordinates) != 5:
        raise VerificationError("mean contractor requires a five-dimensional box")
    pairs = []
    for coordinate, pair in enumerate(coordinates):
        endpoints = tuple(pair)
        if len(endpoints) != 2:
            raise VerificationError(
                "box coordinate %d is not a two-endpoint interval" % coordinate
            )
        lo, hi = endpoints
        if _decimal_fraction(lo) > _decimal_fraction(hi):
            raise VerificationError("box interval is reversed")
        pairs.append((lo, hi))

    l1 = (_decimal_fraction(pairs[0][0]) + _decimal_fraction(pairs[1][0])) / 2
    l2 = (_decimal_fraction(pairs[2][0]) + _decimal_fraction(pairs[3][0])) / 2
    t_cap = _decimal_fraction(t_upper)
    wl, wh = pairs[4]

    if l1 > t_cap and l2 > t_cap:
        return None

    new_wl, new_wh = float(wl), float(wh)
    if l1 > t_cap >= l2:
        cutoff = (t_cap - l2) / (l1 - l2)
        new_wh = min(new_wh, next_decimal_up(cutoff))
    elif l2 > t_cap >= l1:
        cutoff = (l2 - t_cap) / (l2 - l1)
        new_wl = max(new_wl, _next_decimal_down(cutoff))

    if Fraction(repr(new_wl)) > Fraction(repr(new_wh)):
        return None
    if new_wl == float(wl) and new_wh == float(wh):
        return tuple((float(lo), float(hi)) for lo, hi in pairs)
    result = [(float(lo), float(hi)) for lo, hi in pairs]
    result[4] = (new_wl, new_wh)
    return tuple(result)


# ---------------------------------------------------------------------------
# Independent Arb interval primitives
# ---------------------------------------------------------------------------

def _a(value):
    """Construct an outward Arb value using decimal semantics for floats."""
    if isinstance(value, arb):
        return arb(value)
    if isinstance(value, bool):
        raise VerificationError("boolean is not an Arb scalar")
    if isinstance(value, Fraction):
        return arb(value.numerator) / arb(value.denominator)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise VerificationError("non-finite Arb scalar")
        return arb(repr(value))
    return arb(str(value))


def _hull(*values):
    if not values:
        raise VerificationError("empty interval hull")
    result = _a(values[0])
    for value in values[1:]:
        result = result.union(_a(value))
    return result


def _amin(left, right):
    left, right = _a(left), _a(right)
    if left <= right:
        return left
    if right <= left:
        return right
    return _hull(left, right)


def _amax(left, right):
    left, right = _a(left), _a(right)
    if left >= right:
        return left
    if right >= left:
        return right
    return _hull(left, right)


def _abs_upper(value):
    value = _a(value)
    return _amax(-value.lower(), value.upper()).upper()


def _is_zero(value):
    value = _a(value)
    return bool(value.is_exact() and value == ZERO)


def _h_point(value):
    value = _a(value)
    if value <= ZERO or value >= ONE:
        return ZERO
    return -(value * value.log() + (ONE - value) * (ONE - value).log()) / LOG2


def _h_range(lower, upper):
    lower, upper = _a(lower), _a(upper)
    endpoints = _hull(_h_point(lower), _h_point(upper))
    if upper <= HALF or lower >= HALF:
        return endpoints
    return _hull(endpoints, ONE)


def _h_prime(lower, upper):
    lower, upper = _a(lower), _a(upper)
    if not (lower > ZERO and upper < ONE):
        return None
    low_value = ((ONE - upper).log() - upper.log()) / LOG2
    high_value = ((ONE - lower).log() - lower.log()) / LOG2
    return _hull(low_value, high_value)


def _sstar_point(p, q):
    p, q = _a(p), _a(q)
    return _amin(_amax(HALF, _amax(p, q)), _amin(p + q, ONE))


def _sstar_range(pl, ph, ql, qh):
    return _hull(_sstar_point(pl, ql), _sstar_point(ph, qh))


def _rh_range(lower, upper, global_cap=None):
    lower, upper = _a(lower), _a(upper)
    z = _hull(lower, upper)
    hz = _h_range(lower, upper)
    x_lower = (ONE - upper) * (ONE - upper)
    x_upper = (ONE - lower) * (ONE - lower)
    transformed = _h_range(x_lower, x_upper)
    raw = TWO * (ONE - z) * hz - transformed
    lo = _amax(raw.lower(), ZERO)
    hi = _amax(raw.upper(), ZERO)
    if global_cap is not None:
        hi = _amin(hi, global_cap)
    return _hull(lo, hi)


def _sqrt_rh_range(lower, upper, global_cap=None):
    enclosure = _rh_range(lower, upper, global_cap)
    lo = enclosure.lower()
    sqrt_lo = lo.sqrt() if lo > ZERO else ZERO
    hi = _amax(enclosure.upper(), ZERO).upper()
    return _hull(sqrt_lo, hi.sqrt())


def _rh_prime(lower, upper):
    lower, upper = _a(lower), _a(upper)
    hp = _h_prime(lower, upper)
    x_lower = (ONE - upper) * (ONE - upper)
    x_upper = (ONE - lower) * (ONE - lower)
    hp2 = _h_prime(x_lower, x_upper)
    if hp is None or hp2 is None:
        return None
    z = _hull(lower, upper)
    return -TWO * _h_range(lower, upper) + TWO * (ONE - z) * (hp + hp2)


def _positive_rh_range(lower, upper, global_cap):
    lower, upper = _a(lower), _a(upper)
    if not (lower > ZERO and upper < ONE):
        return None
    direct = _rh_range(lower, upper, global_cap)
    if direct.lower() > ZERO:
        return direct
    for subdivisions in (8, 32, 128):
        step = (upper - lower) / subdivisions
        pieces = []
        for index in range(subdivisions):
            left = lower + index * step
            right = lower + (index + 1) * step
            piece = _rh_range(left, right, global_cap)
            if not (piece.lower() > ZERO):
                pieces = None
                break
            pieces.append(piece)
        if pieces is not None:
            return _hull(*pieces)
    return None


def _sqrt_rh_prime(lower, upper, global_cap):
    positive = _positive_rh_range(lower, upper, global_cap)
    derivative = _rh_prime(lower, upper)
    if positive is None or derivative is None:
        return None
    root = positive.sqrt()
    if not root.is_finite() or not (root.lower() > ZERO):
        return None
    result = derivative / (TWO * root)
    return result if result.is_finite() else None


def _rh_global_cover(cells):
    best = ZERO
    for index in range(cells):
        lower = arb(index) / cells
        upper = arb(index + 1) / cells
        cell = _rh_range(lower, upper).upper()
        if not (cell <= best):
            best = _amax(best, cell)
    return best.upper()


def _rho_direct_upper(lower, upper):
    lower, upper = _a(lower), _a(upper)
    transformed_lower = TWO * lower - lower * lower
    transformed_upper = TWO * upper - upper * upper
    numerator_lo = _h_range(transformed_lower, transformed_upper).lower()
    denominator_hi = _h_range(lower, upper).upper()
    return (TWO * (ONE - lower) - numerator_lo / denominator_hi).upper()


def _rho_global_cover(cells):
    if cells < 4:
        raise VerificationError("rho cover requires at least four cells")
    best = ZERO
    for index in range(cells):
        lower = arb(index) / cells
        upper = arb(index + 1) / cells
        candidates = []
        if lower > ZERO and upper < ONE:
            candidates.append(_rho_direct_upper(lower, upper))
        if upper <= HALF and upper > ZERO:
            candidates.append((TWO * upper / _h_point(upper)).upper())
        elif lower >= HALF and lower < ONE:
            candidates.append((TWO * (ONE - lower) / _h_point(lower)).upper())
        if not candidates:
            raise VerificationError("rho cover produced an uncapped cell")
        cell = candidates[0]
        for candidate in candidates[1:]:
            cell = _amin(cell, candidate)
        if not (cell <= best):
            best = _amax(best, cell)
    return best.upper()


def _endpoint_derivative_cap():
    x = arb(1) / 16
    q = ((ONE - x) * (TWO - arb(3) * x + x * x)
         / (TWO * (ONE - x)))
    if not (q > ZERO):
        raise VerificationError("endpoint derivative lemma lost positivity")
    return (ONE / ((ONE - x) * (LOG2 * q).sqrt())).upper()


def _ensure_global_caps():
    global _RH_GLOBAL_CAP, _RHO_GLOBAL_CAP, _DQ_ENDPOINT_CAP
    if (_RH_GLOBAL_CAP is not None and _RHO_GLOBAL_CAP is not None
            and _DQ_ENDPOINT_CAP is not None):
        return _RH_GLOBAL_CAP, _RHO_GLOBAL_CAP, _DQ_ENDPOINT_CAP
    previous = ctx.prec
    try:
        ctx.prec = NATIVE_PREC_BITS
        rh_cap = _rh_global_cover(GLOBAL_COVER_CELLS)
        rho_cap = _rho_global_cover(GLOBAL_COVER_CELLS)
        dq_cap = _endpoint_derivative_cap()
        if not (rh_cap >= arb("0.2342294") and rh_cap <= arb("0.2350")):
            raise VerificationError("independent rh cover failed its locked range")
        if not (rho_cap > ZERO and rho_cap.is_finite()):
            raise VerificationError("independent rho cover is not finite and positive")
        if not (dq_cap > arb("1.2") and dq_cap < arb("1.4")):
            raise VerificationError("endpoint derivative cap failed its locked range")
        _RH_GLOBAL_CAP, _RHO_GLOBAL_CAP, _DQ_ENDPOINT_CAP = rh_cap, rho_cap, dq_cap
    finally:
        ctx.prec = previous
    return _RH_GLOBAL_CAP, _RHO_GLOBAL_CAP, _DQ_ENDPOINT_CAP


def _rho_upper(lower, upper, global_cap):
    lower, upper = _a(lower), _a(upper)
    cap = _a(global_cap)
    if lower > ZERO and upper < ONE:
        cap = _amin(cap, _rho_direct_upper(lower, upper))
    if upper <= HALF and upper > ZERO:
        cap = _amin(cap, (TWO * upper / _h_point(upper)).upper())
    elif lower >= HALF and lower < ONE:
        cap = _amin(cap, (TWO * (ONE - lower) / _h_point(lower)).upper())
    return _amax(cap, ZERO).upper()


@functools.lru_cache(maxsize=262_144)
def _h_float_range(lower, upper):
    return _h_range(_a(lower), _a(upper))


@functools.lru_cache(maxsize=262_144)
def _sqrt_rh_float_range(lower, upper):
    return _sqrt_rh_range(_a(lower), _a(upper), _RH_GLOBAL_CAP)


@functools.lru_cache(maxsize=131_072)
def _sstar_h_float_range(pl, ph, ql, qh):
    sstar = _sstar_range(_a(pl), _a(ph), _a(ql), _a(qh))
    return _h_range(sstar.lower(), sstar.upper())


@functools.lru_cache(maxsize=262_144)
def _rho_float_upper(lower, upper):
    return _rho_upper(_a(lower), _a(upper), _RHO_GLOBAL_CAP)


# ---------------------------------------------------------------------------
# Interval automatic differentiation of Phi
# ---------------------------------------------------------------------------

class AD:
    """An Arb interval value with an interval gradient vector."""

    __slots__ = ("value", "gradient")

    def __init__(self, value, gradient):
        self.value = _a(value)
        self.gradient = tuple(_a(component) for component in gradient)

    @classmethod
    def constant(cls, value, dimension):
        return cls(value, (ZERO,) * dimension)

    @classmethod
    def variable(cls, value, dimension, coordinate):
        gradient = [ZERO] * dimension
        gradient[coordinate] = ONE
        return cls(value, gradient)

    def _coerce(self, other):
        if isinstance(other, AD):
            if len(other.gradient) != len(self.gradient):
                raise VerificationError("automatic-differentiation dimensions differ")
            return other
        return AD.constant(other, len(self.gradient))

    def __add__(self, other):
        other = self._coerce(other)
        return AD(self.value + other.value,
                  (left + right for left, right in zip(self.gradient, other.gradient)))

    __radd__ = __add__

    def __neg__(self):
        return AD(-self.value, (-component for component in self.gradient))

    def __sub__(self, other):
        return self + (-self._coerce(other))

    def __rsub__(self, other):
        return self._coerce(other) - self

    def __mul__(self, other):
        other = self._coerce(other)
        return AD(
            self.value * other.value,
            (left * other.value + self.value * right
             for left, right in zip(self.gradient, other.gradient)),
        )

    __rmul__ = __mul__

    def __truediv__(self, other):
        other = self._coerce(other)
        denominator = other.value * other.value
        return AD(
            self.value / other.value,
            ((left * other.value - self.value * right) / denominator
             for left, right in zip(self.gradient, other.gradient)),
        )

    def __rtruediv__(self, other):
        return self._coerce(other) / self

    def __pow__(self, exponent):
        if exponent != 2:
            raise VerificationError("AD only needs the square operation")
        return self * self


def _ad_all_constant(value):
    return all(_is_zero(component) for component in value.gradient)


def _ad_entropy(value, domain=None):
    lower, upper = (
        domain if domain is not None
        else (value.value.lower(), value.value.upper())
    )
    enclosure = _h_range(lower, upper)
    if _ad_all_constant(value):
        return AD(enclosure, (ZERO,) * len(value.gradient))
    derivative = _h_prime(lower, upper)
    if derivative is None:
        return None
    return AD(enclosure, (derivative * component for component in value.gradient))


def _ad_sqrt_rh(value, global_cap, domain=None):
    lower, upper = (
        domain if domain is not None
        else (value.value.lower(), value.value.upper())
    )
    enclosure = _sqrt_rh_range(lower, upper, global_cap)
    if _ad_all_constant(value):
        return AD(enclosure, (ZERO,) * len(value.gradient))
    derivative = _sqrt_rh_prime(lower, upper, global_cap)
    if derivative is None:
        return None
    return AD(enclosure, (derivative * component for component in value.gradient))


def _sstar_affine_branch(pl, ph, ql, qh):
    if ph <= HALF and qh <= HALF:
        upper_branch = (HALF, HALF, ZERO, ZERO)
    elif pl >= HALF and pl >= qh:
        upper_branch = (pl, ph, ONE, ZERO)
    elif ql >= HALF and ql >= ph:
        upper_branch = (ql, qh, ZERO, ONE)
    else:
        return None

    if ph + qh <= ONE:
        lower_branch = (pl + ql, ph + qh, ONE, ONE)
    elif pl + ql >= ONE:
        lower_branch = (ONE, ONE, ZERO, ZERO)
    else:
        return None

    if upper_branch[1] <= lower_branch[0]:
        return upper_branch
    if lower_branch[1] <= upper_branch[0]:
        return lower_branch
    return None


def _ad_sstar(p, q, p_domain=None, q_domain=None):
    pl, ph = p_domain if p_domain is not None else (
        p.value.lower(), p.value.upper()
    )
    ql, qh = q_domain if q_domain is not None else (
        q.value.lower(), q.value.upper()
    )
    branch = _sstar_affine_branch(pl, ph, ql, qh)
    if branch is not None:
        lower, upper, dp, dq = branch
        result = AD(
            _hull(lower, upper),
            (dp * pg + dq * qg for pg, qg in zip(p.gradient, q.gradient)),
        )
        return result, (lower, upper)

    value = _sstar_range(pl, ph, ql, qh)
    domain = (value.lower(), value.upper())
    if _ad_all_constant(p) and _ad_all_constant(q):
        return AD(value, (ZERO,) * len(p.gradient)), domain

    # At differentiability points the clipped median has one of the gradients
    # 0, grad(p), grad(q), or grad(p)+grad(q).  Their interval hull therefore
    # encloses every a.e. directional derivative needed by the MVT argument.
    gradient = []
    for pg, qg in zip(p.gradient, q.gradient):
        gradient.append(_hull(ZERO, pg, qg, pg + qg))
    return AD(value, gradient), domain


def _normalise_box(box):
    try:
        coordinates = tuple(box)
    except TypeError as exc:
        raise VerificationError("box must be iterable") from exc
    if len(coordinates) != 5:
        raise VerificationError("box must contain exactly five intervals")
    result = []
    for coordinate, pair in enumerate(coordinates):
        try:
            endpoints = tuple(pair)
        except TypeError as exc:
            raise VerificationError("box coordinate is not iterable") from exc
        if len(endpoints) != 2:
            raise VerificationError("box coordinate must have two endpoints")
        try:
            lo, hi = float(endpoints[0]), float(endpoints[1])
        except (TypeError, ValueError, OverflowError) as exc:
            raise VerificationError("box endpoint is not numeric") from exc
        if not (math.isfinite(lo) and math.isfinite(hi)):
            raise VerificationError("box endpoint is not finite")
        if not (0.0 <= lo <= hi <= 1.0):
            raise VerificationError(
                "box coordinate %d is reversed or outside [0,1]" % coordinate
            )
        result.append((lo, hi))
    return tuple(result)


def _prepare_box(box):
    pairs = [(_a(lo), _a(hi)) for lo, hi in box]
    pairs[1] = (_amax(pairs[1][0], pairs[0][0]), pairs[1][1])
    pairs[3] = (_amax(pairs[3][0], pairs[2][0]), pairs[3][1])
    if pairs[1][0] > pairs[1][1] or pairs[3][0] > pairs[3][1]:
        return None
    return tuple(pairs)


def _phi_ad_from_pairs(pairs, t, lam, active_coordinates, global_cap):
    active_coordinates = tuple(active_coordinates)
    dimensions = {coordinate: position
                  for position, coordinate in enumerate(active_coordinates)}
    dimension = len(active_coordinates)
    values = []
    for coordinate, (lower, upper) in enumerate(pairs):
        interval = _hull(lower, upper)
        if coordinate in dimensions:
            values.append(AD.variable(interval, dimension, dimensions[coordinate]))
        else:
            values.append(AD.constant(interval, dimension))
    p1, q1, p2, q2, weight = values
    complement = -weight + ONE

    hp1, hq1 = _ad_entropy(p1, pairs[0]), _ad_entropy(q1, pairs[1])
    hp2, hq2 = _ad_entropy(p2, pairs[2]), _ad_entropy(q2, pairs[3])
    if any(value is None for value in (hp1, hq1, hp2, hq2)):
        return None
    s1, s1_domain = _ad_sstar(p1, q1, pairs[0], pairs[1])
    s2, s2_domain = _ad_sstar(p2, q2, pairs[2], pairs[3])
    c1, c2 = _ad_entropy(s1, s1_domain), _ad_entropy(s2, s2_domain)
    if c1 is None or c2 is None:
        return None
    rp1 = _ad_sqrt_rh(p1, global_cap, pairs[0])
    rq1 = _ad_sqrt_rh(q1, global_cap, pairs[1])
    rp2 = _ad_sqrt_rh(p2, global_cap, pairs[2])
    rq2 = _ad_sqrt_rh(q2, global_cap, pairs[3])
    if any(value is None for value in (rp1, rq1, rp2, rq2)):
        return None

    m1, m2 = (p1 + q1) / TWO, (p2 + q2) / TWO
    l1, l2 = (hp1 + hq1) / TWO, (hp2 + hq2) / TWO
    u1, u2 = (rp1 + rq1) / TWO, (rp2 + rq2) / TWO
    mean = weight * m1 + complement * m2
    entropy = weight * l1 + complement * l2
    correction = weight * c1 + complement * c2
    sigma = weight * u1 + complement * u2
    coefficient = (-mean + ONE) * (TWO * BETA) - ONE
    result = (coefficient * entropy + correction * ALPHA
              - sigma * sigma * BETA + (mean - _a(t)) * _a(lam))
    if not result.value.is_finite():
        return None
    if not all(component.is_finite() for component in result.gradient):
        return None
    return result


def ad_gradient(box, t_decimal, lambda_value):
    """Return the independently generated five-component interval gradient."""
    normalised = _normalise_box(box)
    global_cap, _, _ = _ensure_global_caps()
    previous = ctx.prec
    try:
        ctx.prec = REPLAY_PREC_BITS
        prepared = _prepare_box(normalised)
        if prepared is None:
            return None
        lam = _a(lambda_value)
        if not (lam >= ZERO):
            raise VerificationError("lambda must be certified nonnegative")
        result = _phi_ad_from_pairs(
            prepared, _a(str(t_decimal)), lam, range(5), global_cap
        )
        return None if result is None else result.gradient
    finally:
        ctx.prec = previous


def _centered_bound(pairs, t, lam, active_coordinates, global_cap):
    active_coordinates = tuple(active_coordinates)
    derivative_ad = _phi_ad_from_pairs(
        pairs, t, lam, active_coordinates, global_cap
    )
    if derivative_ad is None:
        return None
    anchor = list(pairs)
    radii = []
    for coordinate in active_coordinates:
        lower, upper = pairs[coordinate]
        midpoint = (lower + upper) / TWO
        anchor[coordinate] = (midpoint, midpoint)
        radii.append((upper - lower) / TWO)
    anchor_ad = _phi_ad_from_pairs(anchor, t, lam, (), global_cap)
    if anchor_ad is None:
        return None
    penalty = ZERO
    for derivative, radius in zip(derivative_ad.gradient, radii):
        penalty += _abs_upper(derivative) * radius
    lower = _a(anchor_ad.value.lower()) - penalty
    return lower if lower.is_finite() else None


def _best_centered(box, t, lambdas, active_coordinates, global_cap):
    prepared = _prepare_box(box)
    if prepared is None:
        return None
    best = None
    for lam in lambdas:
        bound = _centered_bound(
            prepared, t, lam, active_coordinates, global_cap
        )
        if bound is not None and (best is None or bound > best):
            best = bound
    return best


def _orbit_swap(box):
    wl, wh = _a(box[4][0]), _a(box[4][1])
    return (
        box[2],
        box[3],
        box[0],
        box[1],
        ((ONE - wh).lower(), (ONE - wl).upper()),
    )


# ---------------------------------------------------------------------------
# Terminal discharge rules
# ---------------------------------------------------------------------------

def _corner_bound(box, t):
    (p1l, p1h), (q1l, q1h), (p2l, p2h), (q2l, q2h), (wl, wh) = box
    q1l, q2l = max(q1l, p1l), max(q2l, p2l)
    if q1l > q1h or q2l > q2h:
        return None

    p1lo, p1hi = _a(p1l), _a(p1h)
    q1lo, q1hi = _a(q1l), _a(q1h)
    p2lo, p2hi = _a(p2l), _a(p2h)
    q2lo, q2hi = _a(q2l), _a(q2h)
    weight = _hull(_a(wl), _a(wh))
    m1 = _hull((p1lo + q1lo) / TWO, (p1hi + q1hi) / TWO)
    m2 = _hull((p2lo + q2lo) / TWO, (p2hi + q2hi) / TWO)
    mean = weight * m1 + (ONE - weight) * m2
    if mean.lower() > t:
        return None
    m_cap = _amin(mean.upper(), t)
    coefficient = TWO * BETA * (ONE - m_cap) - ONE
    if not (coefficient > ZERO):
        return arb(-1)

    entropy = (
        weight * (_h_float_range(p1l, p1h) + _h_float_range(q1l, q1h)) / TWO
        + (ONE - weight)
        * (_h_float_range(p2l, p2h) + _h_float_range(q2l, q2h)) / TWO
    )
    entropy_lo = _amax(entropy.lower(), ZERO)
    correction = (
        weight * _sstar_h_float_range(p1l, p1h, q1l, q1h)
        + (ONE - weight) * _sstar_h_float_range(p2l, p2h, q2l, q2h)
    )
    correction_lo = _amax(correction.lower(), ZERO)
    sigma1 = (
        _sqrt_rh_float_range(p1l, p1h)
        + _sqrt_rh_float_range(q1l, q1h)
    ) / TWO
    sigma2 = (
        _sqrt_rh_float_range(p2l, p2h)
        + _sqrt_rh_float_range(q2l, q2h)
    ) / TWO
    sigma_hi = (weight * sigma1 + (ONE - weight) * sigma2).upper()
    return (coefficient * entropy_lo + ALPHA * correction_lo
            - BETA * sigma_hi * sigma_hi)


def _ratio_rule(box, t, rho_global_cap):
    weight = _hull(_a(box[4][0]), _a(box[4][1]))
    arho = (
        _rho_float_upper(box[0][0], box[0][1])
        + _rho_float_upper(box[1][0], box[1][1])
    ) / TWO
    brho = (
        _rho_float_upper(box[2][0], box[2][1])
        + _rho_float_upper(box[3][0], box[3][1])
    ) / TWO
    wl, wh = weight.lower(), weight.upper()
    at_lo = (ONE - wl) * brho + wl * arho
    at_hi = (ONE - wh) * brho + wh * arho
    rho_hi = _amax(at_lo.upper(), at_hi.upper())
    kappa = TWO * BETA * (ONE - t) - ONE
    return bool(kappa - BETA * rho_hi >= ZERO)


def _dq_upper(q2_lower):
    _, _, cap = _ensure_global_caps()
    q2_lower = _a(q2_lower)
    if not (q2_lower >= ONE - arb(1) / 16):
        return None
    return cap


def _q2_pin(box, lam, global_cap):
    (p1l, p1h), (q1l, q1h), (p2l, p2h), (q2l, q2h), (wl, wh) = box
    q2l = max(q2l, p2l)
    if q2l > q2h or Fraction(repr(q2l)) < Q2_PIN or p2h > q2l:
        return False
    derivative_cap = _dq_upper(q2l)
    if derivative_cap is None:
        return False

    p1lo, p1hi = _a(p1l), _a(p1h)
    q1lo, q1hi = _a(q1l), _a(q1h)
    p2lo, p2hi = _a(p2l), _a(p2h)
    q2lo = _a(q2l)
    q1lo = _amax(q1lo, p1lo)
    if q1lo > q1hi:
        return True

    weight = _hull(_a(wl), _a(wh))
    complement = ONE - weight
    m1 = _hull((p1lo + q1lo) / TWO, (p1hi + q1hi) / TWO)
    m2 = _hull((p2lo + q2lo) / TWO, (p2hi + ONE) / TWO)
    mean = weight * m1 + complement * m2
    coefficient_lo = (TWO * BETA * (ONE - mean) - ONE).lower()
    if not (coefficient_lo > ZERO):
        return False

    entropy_prime_at_lower = ((ONE - q2lo).log() - q2lo.log()) / LOG2
    complement_lo = _amax(ONE - _a(wh), ZERO)
    complement_hi = _amin(ONE - _a(wl), ONE)
    negative_upper = (
        coefficient_lo * complement_lo / TWO + ALPHA * complement_lo
    ) * entropy_prime_at_lower
    sigma = (
        weight
        * (_sqrt_rh_range(p1lo, p1hi, global_cap)
           + _sqrt_rh_range(q1lo, q1hi, global_cap))
        / TWO
        + complement
        * (_sqrt_rh_range(p2lo, p2hi, global_cap)
           + _sqrt_rh_range(q2lo, ONE, global_cap))
        / TWO
    )
    positive_upper = (
        BETA * sigma.upper() * complement_hi * derivative_cap
        + _a(lam) * complement_hi / TWO
    )
    # The omitted coefficient derivative is -beta*(1-w)*L and is nonpositive.
    return bool(negative_upper + positive_upper <= ZERO)


def _face_pairs(face_box):
    p1, q1, p2, weight = face_box
    return _prepare_box((p1, q1, p2, (1.0, 1.0), weight))


def _face_best_bound(face_box, t, lambdas, global_cap):
    pairs = _face_pairs(face_box)
    if pairs is None:
        return None
    best = None
    for lam in lambdas:
        natural = _phi_ad_from_pairs(pairs, t, lam, (), global_cap)
        if natural is not None:
            candidate = _a(natural.value.lower())
            if best is None or candidate > best:
                best = candidate
        centered = _centered_bound(pairs, t, lam, (0, 1, 2, 4), global_cap)
        if centered is not None and (best is None or centered > best):
            best = centered
    return best


def _split_box(box, coordinate):
    lo, hi = box[coordinate]
    midpoint = (lo + hi) / 2.0
    left, right = list(box), list(box)
    left[coordinate] = (lo, midpoint)
    right[coordinate] = (midpoint, hi)
    return tuple(left), tuple(right)


def _face_branch_and_bound(face_box, t, lambdas, global_cap,
                           min_width, box_budget):
    stack = [face_box]
    counts = Counter()
    while stack:
        if counts["processed"] >= box_budget:
            counts["budget"] += len(stack)
            return False, counts
        box = stack.pop()
        counts["processed"] += 1
        bound = _face_best_bound(box, t, lambdas, global_cap)
        if bound is not None and bound >= ZERO:
            counts["cleared"] += 1
            continue
        widths = [hi - lo for lo, hi in box]
        widest = max(range(4), key=widths.__getitem__)
        if widths[widest] <= min_width:
            counts["residual"] += 1
            return False, counts
        left, right = _split_box(box, widest)
        stack.extend((left, right))
        counts["split"] += 1
    return True, counts


# ---------------------------------------------------------------------------
# Authenticated checkpoints and one-byte replay
# ---------------------------------------------------------------------------

def _canonical_json(value):
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")


def _checkpoint_key(binding):
    return hashlib.sha256(b"uc-independent-checkpoint-v1\0" + _canonical_json(binding)).digest()


def _serialise_box(box):
    return [[repr(float(lo)), repr(float(hi))] for lo, hi in box]


def _deserialise_box(record):
    if not isinstance(record, list) or len(record) != 5:
        raise VerificationError("checkpoint box has the wrong dimension")
    box = []
    for pair in record:
        if not isinstance(pair, list) or len(pair) != 2:
            raise VerificationError("checkpoint box has a malformed interval")
        try:
            lo, hi = float(pair[0]), float(pair[1])
        except (TypeError, ValueError, OverflowError) as exc:
            raise VerificationError("checkpoint endpoint is invalid") from exc
        if not (math.isfinite(lo) and math.isfinite(hi) and 0 <= lo <= hi <= 1):
            raise VerificationError("checkpoint endpoint is out of range")
        if repr(lo) != pair[0] or repr(hi) != pair[1]:
            raise VerificationError("checkpoint endpoint is not canonical")
        box.append((lo, hi))
    return tuple(box)


def _atomic_write(path, payload):
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=".%s." % destination.name, suffix=".tmp", dir=destination.parent
    )
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    except BaseException:
        # Preserve a partial temporary file as failure evidence.  Cleanup is an
        # explicit operator decision, never an implicit verifier side effect.
        raise


def _write_checkpoint(path, binding, trace_offset, stack, counts, eof):
    payload = {
        "schema": "uc-independent-checkpoint-v1",
        "binding": binding,
        "trace_offset": trace_offset,
        "stack": [_serialise_box(box) for box in stack],
        "tallies": {name: int(counts[name]) for name in TALLY_NAMES},
        "eof": bool(eof),
    }
    tag = hmac.new(
        _checkpoint_key(binding), _canonical_json(payload), hashlib.sha256
    ).hexdigest()
    envelope = {"payload": payload, "authentication": {
        "algorithm": "HMAC-SHA256", "tag": tag,
    }}
    _atomic_write(path, _canonical_json(envelope) + b"\n")


def _reject_json_constant(token):
    raise VerificationError("non-finite JSON constant %s" % token)


def _unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise VerificationError("duplicate JSON key %r" % key)
        result[key] = value
    return result


def _decode_json_bytes(raw, label):
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise VerificationError("%s is not UTF-8 JSON" % label) from exc
    try:
        return json.loads(
            text, object_pairs_hook=_unique_object,
            parse_constant=_reject_json_constant,
        )
    except VerificationError:
        raise
    except (json.JSONDecodeError, ValueError, TypeError) as exc:
        raise VerificationError("%s is malformed JSON" % label) from exc


def _validate_runtime_seal(path):
    seal_path = Path(path)
    _regular_file(seal_path, "runtime seal")
    raw = seal_path.read_bytes()
    report = _decode_json_bytes(raw, "runtime seal")
    if (not isinstance(report, dict)
            or report.get("schema") != "uc-runtime-environment-seal-v1"
            or report.get("outcome") != "PASS"
            or report.get("claim_status") != "MACHINE-VERIFIED"):
        raise VerificationError("runtime seal claim envelope is invalid")
    supplied_hash = report.get("report_sha256")
    reduced = {
        key: value for key, value in report.items() if key != "report_sha256"
    }
    if supplied_hash != hashlib.sha256(_canonical_json(reduced)).hexdigest():
        raise VerificationError("runtime seal self-hash differs")
    files = report.get("files")
    if not isinstance(files, list) or not files:
        raise VerificationError("runtime seal file inventory is missing")
    observed_paths = set()
    for record in files:
        if not isinstance(record, dict):
            raise VerificationError("runtime seal file record is malformed")
        file_path = Path(record.get("path", ""))
        resolved = file_path.resolve(strict=True)
        if resolved in observed_paths:
            raise VerificationError("runtime seal repeats a file path")
        observed_paths.add(resolved)
        metadata = _regular_file(resolved, "runtime-sealed file")
        if metadata.st_size != record.get("size"):
            raise VerificationError("runtime-sealed file size differs")
        if _sha256_file(resolved) != record.get("sha256"):
            raise VerificationError("runtime-sealed file SHA-256 differs")
    verifier_record = report.get("independent_verifier")
    current_source = Path(__file__).resolve()
    if (not isinstance(verifier_record, dict)
            or Path(verifier_record.get("path", "")).resolve() != current_source
            or verifier_record.get("size") != current_source.stat().st_size
            or verifier_record.get("sha256") != _sha256_file(current_source)):
        raise VerificationError("runtime seal does not bind this verifier")
    if report.get("file_count") != len(files):
        raise VerificationError("runtime seal file count differs")
    return {
        "path": str(seal_path.resolve()),
        "raw_sha256": hashlib.sha256(raw).hexdigest(),
        "report_sha256": supplied_hash,
        "file_count": len(files),
    }


def _load_checkpoint(path, expected_binding):
    checkpoint_path = Path(path)
    try:
        size = checkpoint_path.stat().st_size
    except OSError as exc:
        raise VerificationError("cannot stat resume checkpoint") from exc
    if size > 512 * 1024 * 1024:
        raise VerificationError("resume checkpoint is unreasonably large")
    try:
        envelope = _decode_json_bytes(checkpoint_path.read_bytes(), "checkpoint")
    except OSError as exc:
        raise VerificationError("cannot read resume checkpoint") from exc
    if not isinstance(envelope, dict) or set(envelope) != {"payload", "authentication"}:
        raise VerificationError("checkpoint envelope has unexpected fields")
    payload, authentication = envelope["payload"], envelope["authentication"]
    if not isinstance(payload, dict) or not isinstance(authentication, dict):
        raise VerificationError("checkpoint envelope has invalid field types")
    if authentication.get("algorithm") != "HMAC-SHA256":
        raise VerificationError("checkpoint authentication algorithm is unsupported")
    supplied = authentication.get("tag")
    if not isinstance(supplied, str) or len(supplied) != 64:
        raise VerificationError("checkpoint authentication tag is malformed")
    binding = payload.get("binding")
    if binding != expected_binding:
        raise VerificationError("checkpoint is bound to different frozen inputs")
    expected = hmac.new(
        _checkpoint_key(expected_binding), _canonical_json(payload), hashlib.sha256
    ).hexdigest()
    if not hmac.compare_digest(supplied, expected):
        raise VerificationError("checkpoint authentication failed")
    if payload.get("schema") != "uc-independent-checkpoint-v1":
        raise VerificationError("checkpoint schema is unsupported")
    offset = payload.get("trace_offset")
    if isinstance(offset, bool) or not isinstance(offset, int) or offset < 0:
        raise VerificationError("checkpoint trace offset is invalid")
    raw_tallies = payload.get("tallies")
    if not isinstance(raw_tallies, dict) or set(raw_tallies) != set(TALLY_NAMES):
        raise VerificationError("checkpoint tallies are malformed")
    counts = Counter()
    for name in TALLY_NAMES:
        value = raw_tallies[name]
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise VerificationError("checkpoint tally is invalid")
        counts[name] = value
    if counts["processed"] != offset:
        raise VerificationError("checkpoint offset and processed tally differ")
    raw_stack = payload.get("stack")
    if not isinstance(raw_stack, list):
        raise VerificationError("checkpoint stack is malformed")
    stack = [_deserialise_box(box) for box in raw_stack]
    eof = payload.get("eof")
    if not isinstance(eof, bool):
        raise VerificationError("checkpoint EOF marker is invalid")
    return offset, stack, counts, eof


def _event_error(event_number, event, message):
    context = ""
    if _ACTIVE_EVENT_CONTEXT is not None:
        raw_box, contracted_box = _ACTIVE_EVENT_CONTEXT
        context = "; raw_box=%r; contracted_box=%r" % (raw_box, contracted_box)
    raise VerificationError(
        "trace event %d (opcode %d): %s%s"
        % (event_number, event, message, context)
    )


def _require_nonnegative(bound, event_number, event, rule):
    if bound is None or not (bound >= ZERO):
        _event_error(
            event_number,
            event,
            "%s did not certify a nonnegative lower bound; bound=%r"
            % (rule, bound),
        )


def _validate_tallies(counts, expected):
    if not isinstance(expected, dict) or set(expected) != set(TALLY_NAMES):
        raise VerificationError("expected replay tallies have the wrong fields")
    for name in TALLY_NAMES:
        value = expected[name]
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise VerificationError("expected replay tally %s is invalid" % name)
        if counts[name] != value:
            raise VerificationError(
                "trace tally mismatch for %s: expected %d, observed %d"
                % (name, value, counts[name])
            )


def replay_trace(trace_path, root_box, t_decimal, lambdas, *,
                 face_min_width=DEFAULT_FACE_MIN_WIDTH,
                 face_box_budget=DEFAULT_FACE_BOX_BUDGET,
                 center_lambdas=None, expected_tallies=None, max_events=None,
                 checkpoint_path=None, resume=False, checkpoint_binding=None):
    """Replay one-byte DFS events and independently verify every terminal.

    The return value contains the replay tallies, pending DFS depth, and EOF
    state.  It does not claim PASS; only :func:`audit_campaign_slice` may do so
    after authenticating the frozen inputs and exact expected tallies.
    """
    global _ACTIVE_EVENT_CONTEXT
    trace_path = Path(trace_path)
    root = _normalise_box(root_box)
    if isinstance(max_events, bool) or (
        max_events is not None
        and (not isinstance(max_events, int) or max_events < 0)
    ):
        raise VerificationError("max_events must be a nonnegative integer or None")
    if (isinstance(face_box_budget, bool)
            or not isinstance(face_box_budget, int) or face_box_budget <= 0):
        raise VerificationError("face_box_budget must be a positive integer")
    try:
        face_min_width = float(face_min_width)
    except (TypeError, ValueError, OverflowError) as exc:
        raise VerificationError("face_min_width must be positive and finite") from exc
    if not math.isfinite(face_min_width) or face_min_width <= 0:
        raise VerificationError("face_min_width must be positive and finite")

    try:
        lambda_texts = tuple(str(value) for value in lambdas)
    except TypeError as exc:
        raise VerificationError("lambda family must be iterable") from exc
    if not lambda_texts:
        raise VerificationError("lambda family must not be empty")
    if center_lambdas is None:
        center_texts = lambda_texts
    else:
        try:
            center_texts = tuple(str(value) for value in center_lambdas)
        except TypeError as exc:
            raise VerificationError("center lambda family must be iterable") from exc
        if not center_texts:
            raise VerificationError("center lambda family must not be empty")

    rh_cap, rho_cap, _ = _ensure_global_caps()
    previous = ctx.prec
    try:
        ctx.prec = REPLAY_PREC_BITS
        t = _a(str(t_decimal))
        if not t.is_finite():
            raise VerificationError("target is not finite")
        t_upper = target_upper_fraction(str(t_decimal))
        if str(t_decimal) == PINNED_TARGET and t_upper != PINNED_TARGET_UPPER:
            raise VerificationError("80-bit target upper endpoint differs from frozen geometry")
        lambda_values = tuple(_a(value) for value in lambda_texts)
        center_values = tuple(_a(value) for value in center_texts)
        if not all(value >= ZERO and value.is_finite() for value in lambda_values):
            raise VerificationError("every launch lambda must be finite and nonnegative")
        if not all(value >= ZERO and value.is_finite() for value in center_values):
            raise VerificationError("every center lambda must be finite and nonnegative")

        binding = checkpoint_binding or {
            "trace": str(trace_path.resolve()),
            "root": _serialise_box(root),
            "target": str(t_decimal),
            "lambdas": list(lambda_texts),
            "center_lambdas": list(center_texts),
            "face_min_width": repr(face_min_width),
            "face_box_budget": face_box_budget,
        }
        if resume:
            if checkpoint_path is None:
                raise VerificationError("resume requires a checkpoint path")
            offset, stack, counts, checkpoint_eof = _load_checkpoint(
                checkpoint_path, binding
            )
            if checkpoint_eof and stack:
                raise VerificationError("EOF checkpoint retains a pending stack")
        else:
            offset, stack, counts, checkpoint_eof = 0, [root], Counter(), False
        initial_trace_offset = offset

        if max_events is not None and offset > max_events:
            raise VerificationError("checkpoint is beyond requested max_events")
        try:
            trace_size = trace_path.stat().st_size
        except OSError as exc:
            raise VerificationError("cannot stat trace") from exc
        if offset > trace_size:
            raise VerificationError("checkpoint offset lies beyond trace EOF")
        if checkpoint_eof != (offset == trace_size):
            raise VerificationError("checkpoint EOF marker disagrees with trace size")

        stopped_by_limit = False
        try:
            trace = trace_path.open("rb")
        except OSError as exc:
            raise VerificationError("cannot open trace") from exc
        with trace:
            trace.seek(offset)
            while offset < trace_size:
                if max_events is not None and counts["processed"] >= max_events:
                    stopped_by_limit = True
                    break
                _ACTIVE_EVENT_CONTEXT = None
                encoded = trace.read(1)
                if len(encoded) != 1:
                    raise VerificationError("trace ended before its authenticated size")
                event = encoded[0]
                event_number = counts["processed"] + 1
                if event not in EVENT_NAMES:
                    _event_error(event_number, event, "unknown trace opcode")
                if not stack:
                    _event_error(event_number, event,
                                 "extra event after DFS stack exhaustion")

                raw = stack.pop()
                counts["processed"] += 1
                offset += 1
                box = contract_mean(raw, t_upper)
                _ACTIVE_EVENT_CONTEXT = (raw, box)

                if event == EVENT_MEAN_INFEASIBLE:
                    if box is not None:
                        _event_error(event_number, event,
                                     "mean contractor did not prove infeasibility")
                    counts["infeasible"] += 1
                elif box is None:
                    _event_error(event_number, event,
                                 "mean contractor proved infeasibility but opcode claims another outcome")
                elif event == EVENT_CORNER_INFEASIBLE:
                    if _corner_bound(box, t) is not None:
                        _event_error(event_number, event,
                                     "corner preparation did not prove infeasibility")
                    counts["infeasible"] += 1
                elif event == EVENT_CORNER:
                    _require_nonnegative(
                        _corner_bound(box, t), event_number, event, "corner rule"
                    )
                    counts["corner"] += 1
                elif event == EVENT_RATIO:
                    if not _ratio_rule(box, t, rho_cap):
                        _event_error(event_number, event,
                                     "decimal-outward ratio rule did not clear the box")
                    counts["ratio"] += 1
                elif event == EVENT_CENTER:
                    _require_nonnegative(
                        _best_centered(box, t, center_values, range(5), rh_cap),
                        event_number, event, "full centered AD rule",
                    )
                    counts["center"] += 1
                elif event == EVENT_CENTER_MIXED:
                    _require_nonnegative(
                        _best_centered(box, t, center_values, (0, 1, 4), rh_cap),
                        event_number, event, "mixed centered AD rule",
                    )
                    counts["center_mixed"] += 1
                elif event == EVENT_CENTER_MIXED_SWAP:
                    _require_nonnegative(
                        _best_centered(
                            _orbit_swap(box), t, center_values, (0, 1, 4), rh_cap
                        ), event_number, event, "swapped-mixed centered AD rule",
                    )
                    counts["center_mixed_swap"] += 1
                elif event == EVENT_CENTER_W:
                    _require_nonnegative(
                        _best_centered(box, t, center_values, (4,), rh_cap),
                        event_number, event, "weight-only centered AD rule",
                    )
                    counts["center_w"] += 1
                elif event == EVENT_FACE:
                    pinned = tuple(
                        lam for lam in lambda_values if _q2_pin(box, lam, rh_cap)
                    )
                    if not pinned:
                        _event_error(event_number, event,
                                     "endpoint derivative cap pinned no launch lambda")
                    face_box = (box[0], box[1], box[2], box[4])
                    complete, _ = _face_branch_and_bound(
                        face_box, t, pinned, rh_cap,
                        face_min_width, face_box_budget,
                    )
                    if not complete:
                        _event_error(event_number, event,
                                     "independent face branch-and-bound did not complete")
                    counts["face"] += 1
                elif event == EVENT_RESIDUAL:
                    _event_error(event_number, event,
                                 "residual leaf is invalid in a complete proof trace")
                elif EVENT_SPLIT_BASE <= event < EVENT_SPLIT_BASE + 5:
                    coordinate = event - EVENT_SPLIT_BASE
                    lo, hi = box[coordinate]
                    left, right = _split_box(box, coordinate)
                    midpoint = left[coordinate][1]
                    if (midpoint != right[coordinate][0]
                            or not (lo < midpoint < hi)):
                        _event_error(event_number, event,
                                     "split midpoint is not strict and representable")
                    stack.extend((left, right))
                    counts["split"] += 1
                else:
                    _event_error(event_number, event, "unsupported trace opcode")

                if (checkpoint_path is not None
                        and counts["processed"] % CHECKPOINT_INTERVAL == 0):
                    _write_checkpoint(
                        checkpoint_path, binding, offset, stack, counts,
                        offset == trace_size,
                    )
                    print(
                        "independent checkpoint: processed=%d pending=%d"
                        % (counts["processed"], len(stack)),
                        flush=True,
                    )

        eof = offset == trace_size
        accounted = sum(counts[name] for name in TALLY_NAMES if name != "processed")
        if accounted != counts["processed"]:
            raise VerificationError(
                "replay tallies account for %d of %d processed events"
                % (accounted, counts["processed"])
            )
        expected_pending = 1 + 2 * counts["split"] - counts["processed"]
        if expected_pending != len(stack):
            raise VerificationError(
                "DFS accounting predicts %d pending boxes, observed %d"
                % (expected_pending, len(stack))
            )
        if eof and counts["processed"] != 2 * counts["split"] + 1:
            raise VerificationError(
                "complete DFS trace violates processed=2*split+1"
            )
        if eof and stack:
            raise VerificationError(
                "trace ended after %d events with %d DFS boxes pending"
                % (counts["processed"], len(stack))
            )
        if not eof and not stopped_by_limit:
            raise VerificationError("trace replay stopped before EOF without an event limit")
        if eof and expected_tallies is not None:
            _validate_tallies(counts, expected_tallies)
        if checkpoint_path is not None:
            _write_checkpoint(checkpoint_path, binding, offset, stack, counts, eof)

        result = {name: int(counts[name]) for name in TALLY_NAMES}
        result.update({
            "pending_stack": len(stack),
            "trace_offset": offset,
            "eof": eof,
            "tallies_verified": bool(eof and expected_tallies is not None),
            "initial_trace_offset": initial_trace_offset,
            "resume_used": bool(resume),
        })
        return result
    finally:
        ctx.prec = previous


# ---------------------------------------------------------------------------
# Frozen-input audit, reports, and CLI
# ---------------------------------------------------------------------------

def _sha256_file(path):
    digest = hashlib.sha256()
    try:
        with Path(path).open("rb") as stream:
            while True:
                block = stream.read(1024 * 1024)
                if not block:
                    break
                digest.update(block)
    except OSError as exc:
        raise VerificationError("cannot hash %s" % path) from exc
    return digest.hexdigest()


def _regular_file(path, label):
    path = Path(path)
    try:
        metadata = path.lstat()
    except OSError as exc:
        raise VerificationError("cannot stat %s" % label) from exc
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
        raise VerificationError("%s must be a regular non-symlink file" % label)
    return metadata


def _safe_campaign_member(campaign, relative, label):
    if not isinstance(relative, str) or not relative:
        raise VerificationError("%s path is invalid" % label)
    pure = PurePosixPath(relative)
    if pure.is_absolute() or ".." in pure.parts or "." in pure.parts:
        raise VerificationError("%s path escapes the campaign" % label)
    candidate = campaign.joinpath(*pure.parts)
    resolved_campaign = campaign.resolve()
    try:
        resolved = candidate.resolve(strict=True)
    except OSError as exc:
        raise VerificationError("cannot resolve %s" % label) from exc
    if resolved.parent != resolved_campaign and resolved_campaign not in resolved.parents:
        raise VerificationError("%s resolves outside the campaign" % label)
    return candidate


def _verify_record(path, record, label):
    if not isinstance(record, dict):
        raise VerificationError("%s lock record is not an object" % label)
    expected_fields = {"path", "raw_sha256", "size"}
    if not expected_fields.issubset(record):
        raise VerificationError("%s lock record is incomplete" % label)
    metadata = _regular_file(path, label)
    size = record["size"]
    if isinstance(size, bool) or not isinstance(size, int) or size < 0:
        raise VerificationError("%s locked size is invalid" % label)
    if metadata.st_size != size:
        raise VerificationError("%s size differs from the lock" % label)
    observed = _sha256_file(path)
    expected = record["raw_sha256"]
    if not isinstance(expected, str) or observed != expected:
        raise VerificationError("%s SHA-256 differs from the lock" % label)
    return observed


def _verify_snapshot(campaign, snapshot):
    if not isinstance(snapshot, dict) or not snapshot:
        raise VerificationError("lock snapshot is missing")
    verified = {}
    for name in sorted(snapshot):
        record = snapshot[name]
        if not isinstance(record, dict) or set(record) != {"path", "sha256", "size"}:
            raise VerificationError("snapshot record %s is malformed" % name)
        path = _safe_campaign_member(campaign, record["path"], "snapshot %s" % name)
        metadata = _regular_file(path, "snapshot %s" % name)
        if metadata.st_size != record["size"]:
            raise VerificationError("snapshot %s size differs from lock" % name)
        digest = _sha256_file(path)
        if digest != record["sha256"]:
            raise VerificationError("snapshot %s SHA-256 differs from lock" % name)
        verified[name] = digest
    return verified


def _embedded_hash(document, field, expected, label):
    if not isinstance(document, dict):
        raise VerificationError("%s is not a JSON object" % label)
    supplied = document.get(field)
    if not isinstance(supplied, str):
        raise VerificationError("%s lacks %s" % (label, field))
    payload = dict(document)
    del payload[field]
    observed = hashlib.sha256(_canonical_json(payload)).hexdigest()
    if supplied != observed or supplied != expected:
        raise VerificationError("%s canonical object hash is invalid" % label)


def _load_frozen_configuration(lock_path, campaign_path, slice_index):
    lock_path, campaign = Path(lock_path), Path(campaign_path)
    _regular_file(lock_path, "campaign lock")
    lock_raw = lock_path.read_bytes()
    lock = _decode_json_bytes(lock_raw, "campaign lock")
    lock_sha = hashlib.sha256(lock_raw).hexdigest()
    if not isinstance(lock, dict) or lock.get("schema") != "uc-campaign-lock-v1":
        raise VerificationError("campaign lock schema is unsupported")
    expected_environment = lock.get("expected_environment")
    if not isinstance(expected_environment, dict):
        raise VerificationError("campaign lock lacks expected environment")
    try:
        flint_version = importlib_metadata.version("python-flint")
    except importlib_metadata.PackageNotFoundError as exc:
        raise VerificationError("python-flint distribution metadata is unavailable") from exc
    observed_environment = {
        "python": platform.python_version(),
        "python_implementation": sys.implementation.name,
        "platform": platform.platform(),
        "flint": flint_version,
    }
    if observed_environment["python"] != expected_environment.get("python"):
        raise VerificationError("Python version differs from campaign lock")
    if (observed_environment["python_implementation"].lower()
            != str(expected_environment.get("python_implementation", "")).lower()):
        raise VerificationError("Python implementation differs from campaign lock")
    if observed_environment["platform"] != expected_environment.get("platform"):
        raise VerificationError("platform identity differs from campaign lock")
    if observed_environment["flint"] != expected_environment.get("flint"):
        raise VerificationError("python-flint version differs from campaign lock")
    try:
        resolved_campaign = campaign.resolve(strict=True)
    except OSError as exc:
        raise VerificationError("campaign directory cannot be resolved") from exc
    if not resolved_campaign.is_dir() or campaign.is_symlink():
        raise VerificationError("campaign must be a real directory, not a symlink")
    if resolved_campaign.name != lock.get("campaign_directory_name"):
        raise VerificationError("campaign directory name differs from lock")
    if isinstance(slice_index, bool) or not isinstance(slice_index, int):
        raise VerificationError("slice must be an integer")
    slices = lock.get("slices")
    if not isinstance(slices, list) or not (0 <= slice_index < len(slices)):
        raise VerificationError("slice is outside the locked campaign range")
    slice_record = slices[slice_index]
    if not isinstance(slice_record, dict) or slice_record.get("slice") != slice_index:
        raise VerificationError("slice lock record is malformed")

    launch_record = lock.get("launch")
    launch_path = _safe_campaign_member(
        resolved_campaign, launch_record.get("path") if isinstance(launch_record, dict) else None,
        "launch",
    )
    launch_sha = _verify_record(launch_path, launch_record, "launch")
    launch = _decode_json_bytes(launch_path.read_bytes(), "launch")
    _embedded_hash(launch, "launch_sha256", launch_record.get("object_sha256"), "launch")
    if launch.get("campaign_id") != lock.get("campaign_id"):
        raise VerificationError("launch campaign id differs from lock")
    if launch.get("code_sha256") != lock.get("code_sha256"):
        raise VerificationError("launch code hash differs from lock")
    if launch.get("schema") != "cert3-campaign-v2":
        raise VerificationError("launch schema is unsupported")

    _verify_snapshot(resolved_campaign, lock.get("snapshot"))

    runs = launch.get("runs")
    if not isinstance(runs, list) or len(runs) != len(slices):
        raise VerificationError("launch runs do not match locked slices")
    run = runs[slice_index]
    if not isinstance(run, dict) or run.get("slice") != slice_index:
        raise VerificationError("launch run does not match requested slice")
    if run.get("run_id") != slice_record.get("run_id"):
        raise VerificationError("launch run id differs from lock")

    trace_record = slice_record.get("trace")
    if not isinstance(trace_record, dict) or trace_record.get("schema") != "cert3-trace-v1":
        raise VerificationError("trace lock record is malformed")
    trace_path = _safe_campaign_member(
        resolved_campaign, trace_record.get("path"), "trace"
    )
    trace_metadata = _regular_file(trace_path, "trace")
    if trace_metadata.st_size != trace_record.get("size"):
        raise VerificationError("trace size differs from lock")
    trace_sha = _sha256_file(trace_path)
    if trace_sha != trace_record.get("sha256"):
        raise VerificationError("trace SHA-256 differs from lock")
    if run.get("trace_filename") != trace_record.get("path"):
        raise VerificationError("launch trace filename differs from lock")

    result_record = slice_record.get("result")
    result_path = _safe_campaign_member(
        resolved_campaign,
        result_record.get("path") if isinstance(result_record, dict) else None,
        "result",
    )
    result_sha = _verify_record(result_path, result_record, "result")
    result = _decode_json_bytes(result_path.read_bytes(), "result")
    _embedded_hash(result, "record_sha256", result_record.get("record_sha256"), "result")
    if (result.get("result_schema") != "cert3-result-v2"
            or result.get("slice") != slice_index
            or result.get("run_id") != slice_record.get("run_id")
            or result.get("campaign_id") != lock.get("campaign_id")
            or result.get("trace_sha256") != trace_sha
            or result.get("trace_size") != trace_metadata.st_size
            or result.get("trace_schema") != "cert3-trace-v1"
            or result.get("complete") is not True
            or result.get("returned_normally") is not True
            or result.get("supervisor_committed") is not True
            or result.get("verdict") != "COMPLETE"):
        raise VerificationError("frozen result metadata is not a committed COMPLETE run")

    parameters = launch.get("parameters")
    if not isinstance(parameters, dict):
        raise VerificationError("launch parameters are missing")
    if parameters.get("work_prec_bits") != REPLAY_PREC_BITS:
        raise VerificationError("launch does not lock 80-bit replay arithmetic")
    if parameters.get("alpha") != ALPHA_TEXT:
        raise VerificationError("launch alpha differs from independent formula")
    if Fraction(str(parameters.get("q2pin"))) != Q2_PIN:
        raise VerificationError("launch q2 pin differs from endpoint lemma")
    t_decimal = parameters.get("t_decimal")
    if t_decimal != launch.get("t_decimal") or t_decimal != result.get("t_decimal"):
        raise VerificationError("target decimal differs across frozen inputs")
    t_upper = target_upper_fraction(t_decimal)
    if t_decimal == PINNED_TARGET and t_upper != PINNED_TARGET_UPPER:
        raise VerificationError("pinned 80-bit target upper endpoint changed")

    lambda_family = parameters.get("lambda_family")
    if not isinstance(lambda_family, list) or not lambda_family:
        raise VerificationError("launch lambda family is missing")
    lambda_family = tuple(str(value) for value in lambda_family)
    previous = ctx.prec
    try:
        ctx.prec = REPLAY_PREC_BITS
        if not all(_a(value).is_finite() and _a(value) >= ZERO
                   for value in lambda_family):
            raise VerificationError("launch contains a negative or non-finite lambda")
    finally:
        ctx.prec = previous
    if not all(value in lambda_family for value in PINNED_CENTER_LAMBDAS):
        raise VerificationError("pinned center lambdas are absent from launch family")

    try:
        w_lo, w_hi = Fraction(slice_record["w_lo"]), Fraction(slice_record["w_hi"])
    except (KeyError, ValueError, TypeError, ZeroDivisionError) as exc:
        raise VerificationError("slice weight interval is malformed") from exc
    if run.get("w_lo") != slice_record.get("w_lo") or run.get("w_hi") != slice_record.get("w_hi"):
        raise VerificationError("launch and lock weight intervals differ")
    if not (Fraction(0) <= w_lo < w_hi <= Fraction(1)):
        raise VerificationError("slice weight interval is invalid")
    root = ((0.0, 1.0),) * 4 + ((float(w_lo), float(w_hi)),)

    expected = slice_record.get("expected_replay_tallies")
    if not isinstance(expected, dict) or set(expected) != set(TALLY_NAMES):
        raise VerificationError("locked replay tallies are malformed")
    result_tallies = result.get("tallies")
    if not isinstance(result_tallies, dict):
        raise VerificationError("result tallies are missing")
    for name in TALLY_NAMES:
        if result_tallies.get(name) != expected[name]:
            raise VerificationError("result tally %s differs from lock" % name)
    completion = slice_record.get("expected_completion_tallies")
    if completion != {"budget_boxes": 0, "budget_time": 0, "stack": 0}:
        raise VerificationError("completion tallies do not certify an empty DFS stack")
    if expected["processed"] != trace_metadata.st_size:
        raise VerificationError("processed tally differs from one-byte trace size")

    face_min_width = parameters.get("face_min_width")
    face_box_budget = parameters.get("face_box_budget")
    try:
        face_min_width = float(face_min_width)
    except (TypeError, ValueError, OverflowError) as exc:
        raise VerificationError("launch face width is invalid") from exc
    if (not math.isfinite(face_min_width) or face_min_width <= 0
            or isinstance(face_box_budget, bool)
            or not isinstance(face_box_budget, int) or face_box_budget <= 0):
        raise VerificationError("launch face branch-and-bound limits are invalid")

    verifier_sha = _sha256_file(Path(__file__).resolve())
    binding = {
        "schema": "uc-independent-checkpoint-binding-v1",
        "verifier_sha256": verifier_sha,
        "lock_sha256": lock_sha,
        "launch_raw_sha256": launch_sha,
        "trace_sha256": trace_sha,
        "trace_size": trace_metadata.st_size,
        "result_raw_sha256": result_sha,
        "campaign_id": lock["campaign_id"],
        "run_id": slice_record["run_id"],
        "slice": slice_index,
        "target": t_decimal,
        "target_upper_numerator": str(t_upper.numerator),
        "target_upper_denominator": str(t_upper.denominator),
        "root": _serialise_box(root),
        "lambdas": list(lambda_family),
        "center_lambdas": list(PINNED_CENTER_LAMBDAS),
        "face_min_width": repr(face_min_width),
        "face_box_budget": face_box_budget,
    }
    return {
        "lock": lock,
        "lock_path": lock_path,
        "launch_path": launch_path,
        "result_path": result_path,
        "environment": observed_environment,
        "lock_sha256": lock_sha,
        "launch_sha256": launch_sha,
        "trace_sha256": trace_sha,
        "result_sha256": result_sha,
        "trace_path": trace_path,
        "trace_metadata": trace_metadata,
        "root": root,
        "t_decimal": t_decimal,
        "t_upper": t_upper,
        "lambdas": lambda_family,
        "center_lambdas": PINNED_CENTER_LAMBDAS,
        "face_min_width": face_min_width,
        "face_box_budget": face_box_budget,
        "expected": expected,
        "binding": binding,
        "slice_record": slice_record,
        "verifier_sha256": verifier_sha,
    }


def _seal_report(report):
    sealed = dict(report)
    sealed.pop("report_sha256", None)
    sealed["report_sha256"] = hashlib.sha256(_canonical_json(sealed)).hexdigest()
    return sealed


def audit_campaign_slice(
    lock_path,
    campaign_path,
    slice_index,
    *,
    runtime_seal_path,
    max_events=None,
    checkpoint_path=None,
    resume=False,
):
    """Authenticate and replay one campaign slice.

    A finite ``max_events`` always yields ``PARTIAL_AUDIT`` by policy, even if
    the supplied bound reaches EOF.  PASS additionally requires authenticated
    EOF, an empty DFS stack, and exact locked tallies.
    """
    if resume and max_events is None:
        raise VerificationError(
            "checkpoint resume is integrity-only and cannot produce a full PASS"
        )
    started = time.monotonic()
    started_utc = _datetime.datetime.now(_datetime.timezone.utc).isoformat()
    runtime_seal = _validate_runtime_seal(runtime_seal_path)
    configuration = _load_frozen_configuration(
        lock_path, campaign_path, slice_index
    )
    configuration["binding"] = dict(configuration["binding"])
    configuration["binding"]["runtime_seal_raw_sha256"] = runtime_seal[
        "raw_sha256"
    ]
    replay = replay_trace(
        configuration["trace_path"],
        configuration["root"],
        configuration["t_decimal"],
        configuration["lambdas"],
        face_min_width=configuration["face_min_width"],
        face_box_budget=configuration["face_box_budget"],
        center_lambdas=configuration["center_lambdas"],
        expected_tallies=configuration["expected"],
        max_events=max_events,
        checkpoint_path=checkpoint_path,
        resume=resume,
        checkpoint_binding=configuration["binding"],
    )
    current_verifier_sha = _sha256_file(Path(__file__).resolve())
    if current_verifier_sha != configuration["verifier_sha256"]:
        raise VerificationError("verifier source changed during replay")
    current_trace = _regular_file(configuration["trace_path"], "trace")
    original_trace = configuration["trace_metadata"]
    if (current_trace.st_dev, current_trace.st_ino, current_trace.st_size,
            current_trace.st_mtime_ns) != (
            original_trace.st_dev, original_trace.st_ino,
            original_trace.st_size, original_trace.st_mtime_ns):
        raise VerificationError("trace file changed during replay")
    if _sha256_file(configuration["trace_path"]) != configuration["trace_sha256"]:
        raise VerificationError("trace SHA-256 changed during replay")
    for label, path, expected_sha in (
        ("campaign lock", configuration["lock_path"], configuration["lock_sha256"]),
        ("launch", configuration["launch_path"], configuration["launch_sha256"]),
        ("result", configuration["result_path"], configuration["result_sha256"]),
    ):
        if _sha256_file(path) != expected_sha:
            raise VerificationError("%s SHA-256 changed during replay" % label)
    if _validate_runtime_seal(runtime_seal_path) != runtime_seal:
        raise VerificationError("runtime seal or sealed bytes changed during replay")

    arithmetic_complete = bool(
        replay["eof"]
        and replay["pending_stack"] == 0
        and replay["tallies_verified"]
        and replay["initial_trace_offset"] == 0
        and replay["resume_used"] is False
    )
    if max_events is None:
        if not arithmetic_complete:
            raise VerificationError("full replay did not meet PASS conditions")
        outcome = "PASS"
    else:
        outcome = "PARTIAL_AUDIT"

    report = {
        "schema": "uc-independent-arithmetic-report-v1",
        "outcome": outcome,
        "claim_status": (
            "MACHINE-VERIFIED" if outcome == "PASS"
            else "COMPUTATIONAL-EVIDENCE"
        ),
        "campaign_id": configuration["lock"]["campaign_id"],
        "run_id": configuration["slice_record"]["run_id"],
        "slice": slice_index,
        "processed": replay["processed"],
        "pending_stack": replay["pending_stack"],
        "trace_offset": replay["trace_offset"],
        "trace_eof": replay["eof"],
        "arithmetic_complete": arithmetic_complete,
        "finite_event_limit": max_events,
        "tallies": {name: replay[name] for name in TALLY_NAMES},
        "expected_tallies_authenticated": replay["tallies_verified"],
        "initial_trace_offset": replay["initial_trace_offset"],
        "resume_used": replay["resume_used"],
        "implementation": {
            "gradient_engine": "interval automatic differentiation",
            "imports_frozen_arithmetic": False,
            "rediscover_face_proofs": True,
            "shares_python_flint": True,
            "byte_zero_required_for_pass": True,
        },
        "precision": {
            "global_cover_bits": NATIVE_PREC_BITS,
            "replay_bits": REPLAY_PREC_BITS,
            "cover_cells": GLOBAL_COVER_CELLS,
        },
        "target": {
            "decimal": configuration["t_decimal"],
            "upper_fraction": "%d/%d" % (
                configuration["t_upper"].numerator,
                configuration["t_upper"].denominator,
            ),
        },
        "input_sha256": {
            "lock": configuration["lock_sha256"],
            "launch": configuration["launch_sha256"],
            "trace": configuration["trace_sha256"],
            "result": configuration["result_sha256"],
            "verifier": configuration["verifier_sha256"],
        },
        "runtime_seal": runtime_seal,
        "environment": configuration["environment"],
        "limitations": [
            "The verifier consumes the same authenticated one-byte DFS trace partition.",
            "The verifier and campaign both rely on python-flint's Arb primitive library.",
            "No frozen campaign Python arithmetic module is imported or executed.",
            "Nonnegative lambda values are authenticated launch inputs, not independently rediscovered optimizers.",
        ],
        "elapsed_seconds": time.monotonic() - started,
        "started_utc": started_utc,
        "finished_utc": _datetime.datetime.now(
            _datetime.timezone.utc
        ).isoformat(),
    }
    return _seal_report(report)


def _failure_report(error, arguments):
    text = str(error)
    event_match = re.search(r"trace event ([0-9]+) \(opcode ([0-9]+)\)", text)
    report = {
        "schema": "uc-independent-arithmetic-report-v1",
        "outcome": "FAIL",
        "claim_status": "FAILED",
        "error_type": type(error).__name__,
        "error": text,
        "slice": getattr(arguments, "slice", None),
        "processed": (
            int(event_match.group(1)) - 1 if event_match is not None else None
        ),
        "failing_event": (
            int(event_match.group(1)) if event_match is not None else None
        ),
        "failing_opcode": (
            int(event_match.group(2)) if event_match is not None else None
        ),
        "pending_stack": None,
        "input_sha256": {
            "verifier": _sha256_file(Path(__file__).resolve()),
        },
        "finished_utc": _datetime.datetime.now(
            _datetime.timezone.utc
        ).isoformat(),
    }
    return _seal_report(report)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Independently replay one authenticated UC Campaign I slice"
    )
    parser.add_argument("--lock", required=True)
    parser.add_argument("--campaign", required=True)
    parser.add_argument("--slice", required=True, type=int)
    parser.add_argument("--output", required=True)
    parser.add_argument("--runtime-seal", required=True)
    parser.add_argument("--checkpoint")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--max-events", type=int)
    arguments = parser.parse_args(argv)
    if arguments.resume and not arguments.checkpoint:
        parser.error("--resume requires --checkpoint")
    print(
        "independent arithmetic replay START slice=%d%s"
        % (
            arguments.slice,
            " resume" if arguments.resume else "",
        ),
        flush=True,
    )

    try:
        report = audit_campaign_slice(
            arguments.lock,
            arguments.campaign,
            arguments.slice,
            runtime_seal_path=arguments.runtime_seal,
            max_events=arguments.max_events,
            checkpoint_path=arguments.checkpoint,
            resume=arguments.resume,
        )
        _atomic_write(arguments.output, _canonical_json(report) + b"\n")
    except Exception as exc:
        failure = _failure_report(exc, arguments)
        try:
            _atomic_write(arguments.output, _canonical_json(failure) + b"\n")
        except OSError:
            pass
        print("independent arithmetic replay FAIL: %s" % exc, file=sys.stderr)
        return 1

    if report["outcome"] != "PASS":
        print("independent arithmetic replay PARTIAL_AUDIT", file=sys.stderr)
        return 2
    print("independent arithmetic replay PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
