/-
This file was generated by Aristotle,
with some modifications.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d09fcaec-86ec-46f2-b099-308960f47f8c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formalized the generalization of Boppana's entropy inequality as conjectured by Yuster and proved in the provided note.
The main result is `generalized_boppana_full`, which states that for real $k > 1$, $\alpha_k h(x^k) \ge x^{k-1} h(x)$ for $x \in [0, 1]$, with equality if and only if $x \in \{0, 1, 1/(1+\alpha_k)\}$.
Here $\alpha_k$ is the unique positive solution to $x(1+x)^{k-1}=1$.
The proof follows the structure of the paper, utilizing the auxiliary function $q(x) = x^{k-1}h(x)/h(x^k)$ and analyzing its critical points via the function $G(x) = \log(x)\log(1-x)/h(x)$.
Key lemmas such as the monotonicity of $G$ and the properties of $\alpha_k$ were assumed as per the provided context, and we formalized the final assembly of the proof.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

-- #check Real.binEntropy

/-
For $k > 1$, $\alpha_k$ is the unique positive solution to $x(1+x)^{k-1}=1$.
-/
lemma alpha_exists (k : ℝ) (hk : k > 1) :
    ∃ x : ℝ, x > 0 ∧ x * (1 + x) ^ (k - 1) = 1 := by
  -- By the Intermediate Value Theorem, since $f(0) = 0$ and $f(1) = 2^{k - 1} > 1$.
  have h_image :
      (1 : ℝ) ∈ (fun x : ℝ => x * (1 + x) ^ (k - 1)) '' Set.Ioo (0 : ℝ) 1 := by
    refine
      (intermediate_value_Ioo (a := (0 : ℝ)) (b := (1 : ℝ))
          (f := fun x : ℝ => x * (1 + x) ^ (k - 1)) (by norm_num) ?_) ?_
    ·
      exact
        continuousOn_of_forall_continuousAt fun x hx =>
          ContinuousAt.mul continuousAt_id <|
            ContinuousAt.rpow (continuousAt_const.add continuousAt_id) continuousAt_const <|
              Or.inl <| by linarith [hx.1]
    · constructor
      · norm_num
      ·
        have hpow : (1 : ℝ) < (1 + 1) ^ (k - 1) := by
          exact Real.one_lt_rpow (by norm_num : (1 : ℝ) < (1 + 1)) (by linarith [hk])
        simpa using hpow
  rcases h_image with ⟨x, hx, hx_eq⟩
  exact ⟨x, hx.1, hx_eq⟩

noncomputable def alpha (k : ℝ) : ℝ :=
  if hk : k > 1 then
    Classical.choose (alpha_exists k hk)
  else 0

lemma alpha_spec (k : ℝ) (hk : k > 1) :
    alpha k > 0 ∧ alpha k * (1 + alpha k) ^ (k - 1) = 1 := by
  unfold alpha
  simpa [hk] using (Classical.choose_spec (alpha_exists k hk))

lemma alpha_pos (k : ℝ) (hk : k > 1) : 0 < alpha k :=
  (alpha_spec k hk).1

/-
For $k > 1$, $\alpha_k > 1/k$.
-/
lemma lemma_l2 (k : ℝ) (hk : k > 1) : alpha k > 1 / k := by
  -- Set $f(x) = x(1+x)^{k-1}$.
  set f := fun x : ℝ => x * (1 + x) ^ (k - 1);
  -- Since $f$ is strictly increasing on $(0, \infty)$, it suffices to check that $f(1/k) < 1$.
  have h_f1k_lt_1 : f (1 / k) < 1 := by
    -- Simplify $f(1/k)$ to get $(1/k) * (1 + 1/k)^{k-1} < 1$.
    have h_simplified : (1 / k) * (1 + 1 / k) ^ (k - 1) < 1 := by
      -- Simplify the expression $(1 / k) * (1 + 1 / k) ^ (k - 1)$ to $(1 + 1 / k) ^ (k - 1) / k$.
      suffices h_simplified' : (1 + 1 / k) ^ (k - 1) < k by
        rw [ div_mul_eq_mul_div, div_lt_iff₀ ] <;> linarith;
      -- Taking the natural logarithm of both sides, we need to show that $(k-1) \ln(1 + 1/k) < \ln(k)$.
      suffices h_ln : (k - 1) * Real.log (1 + 1 / k) < Real.log k by
        rw [ ← Real.log_lt_log_iff ( by positivity ) ( by positivity ), Real.log_rpow ( by positivity ) ] ; linarith;
      -- We'll use the fact that $Real.log (1 + x) < x$ for all $x > 0$.
      have h_log_lt : Real.log (1 + 1 / k) < 1 / k := by
        simpa using Real.log_lt_sub_one_of_pos ( add_pos zero_lt_one ( one_div_pos.mpr ( zero_lt_one.trans hk ) ) ) ( by nlinarith [ one_div_mul_cancel ( by linarith : k ≠ 0 ) ] );
      rw [ lt_div_iff₀ ] at h_log_lt <;> nlinarith [ Real.log_inv k ▸ Real.log_lt_sub_one_of_pos ( inv_pos.mpr <| zero_lt_one.trans hk ) ( by nlinarith [ inv_mul_cancel₀ ( ne_of_gt <| zero_lt_one.trans hk ) ] ), mul_inv_cancel₀ ( ne_of_gt <| zero_lt_one.trans hk ) ];
    exact h_simplified;
  -- Since $f$ is strictly increasing on $(0, \infty)$, we have $f(\alpha_k) = 1$.
  have h_f_alpha_k : f (alpha k) = 1 := by
    simpa [f] using (alpha_spec k hk).2
  -- Since $f$ is strictly increasing on $(0, \infty)$, we have $f(\alpha_k) > f(1/k)$.
  have h_f_alpha_k_gt_f1k : f (alpha k) > f (1 / k) := by
    linarith;
  have hα_nonneg : 0 ≤ alpha k := (alpha_pos k hk).le
  have hk0 : k ≠ 0 := by linarith
  contrapose! h_f_alpha_k_gt_f1k;
  exact
    mul_le_mul
      (by nlinarith [mul_div_cancel₀ 1 hk0])
      (Real.rpow_le_rpow
        (by nlinarith [mul_div_cancel₀ 1 hk0, hα_nonneg])
        (by nlinarith [mul_div_cancel₀ 1 hk0, hα_nonneg])
        (by linarith))
      (by exact Real.rpow_nonneg (by nlinarith [mul_div_cancel₀ 1 hk0, hα_nonneg]) _)
      (by nlinarith [mul_div_cancel₀ 1 hk0, hα_nonneg])

/-
We have $\lim_{x\to 0^+}q(x)=1/k$.
-/
noncomputable def q (k : ℝ) (x : ℝ) : ℝ := x ^ (k - 1) * Real.binEntropy x / Real.binEntropy (x ^ k)

lemma lemma_l1_zero (k : ℝ) (hk : k > 1) :
    Filter.Tendsto (q k) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / k)) := by
  unfold q;
  -- We'll use the fact that $h(x) = -x \log x + O(x)$ as $x \to 0$.
  have h_hx : Filter.Tendsto (fun x : ℝ => Real.binEntropy x / (-x * Real.log x)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
    -- We'll use the fact that $h(x) = -x \log x + O(x^2)$ to simplify the expression.
    have h_binEntropy_approx : Filter.Tendsto (fun x => (Real.binEntropy x - (-x * Real.log x)) / (-x * Real.log x)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
      -- We'll use the fact that $h(x) = -x \log x + O(x^2)$ to simplify the expression. Notice that $Real.binEntropy x = -x \log x - (1 - x) \log (1 - x)$.
      have h_binEntropy_approx : Filter.Tendsto (fun x => (-(1 - x) * Real.log (1 - x)) / (-x * Real.log x)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
        -- We'll use the fact that $\log(1 - x) \sim -x$ as $x \to 0$ to simplify the expression.
        have h_log_approx : Filter.Tendsto (fun x => Real.log (1 - x) / x) (nhdsWithin 0 (Set.Ioi 0)) (nhds (-1)) := by
          simpa [ div_eq_inv_mul ] using HasDerivAt.tendsto_slope_zero_right ( HasDerivAt.log ( hasDerivAt_id 0 |> HasDerivAt.const_sub 1 ) ( by norm_num ) );
        -- We'll use the fact that $(1 - x) \to 1$ as $x \to 0$.
        have h_one_minus_x : Filter.Tendsto (fun x : ℝ => (1 - x)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
          exact tendsto_nhdsWithin_of_tendsto_nhds ( Continuous.tendsto' ( by continuity ) _ _ <| by norm_num );
        convert h_one_minus_x.mul ( h_log_approx.div_atBot ( Real.tendsto_log_nhdsNE_zero.mono_left <| nhdsWithin_mono _ <| by norm_num ) ) using 2 <;> ring!;
      simp_all +decide [ Real.binEntropy ];
      exact h_binEntropy_approx.congr fun x => by ring;
    have := h_binEntropy_approx.const_add 1;
    simpa using this.congr' ( by filter_upwards [ ( Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, zero_lt_one ⟩ ) ] with x hx using by rw [ one_add_div ( mul_ne_zero ( neg_ne_zero.mpr hx.1.ne' ) <| ne_of_lt <| Real.log_neg hx.1 hx.2 ) ] ; ring );
  -- Applying the asymptotic estimate to $h(x^k)$, we get $h(x^k) = -kx^k \log x + O(x^k)$.
  have h_hxk : Filter.Tendsto (fun x : ℝ => Real.binEntropy (x ^ k) / (-k * x ^ k * Real.log x)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
    have h_hxk : Filter.Tendsto (fun x : ℝ => (Real.binEntropy (x ^ k)) / (-x ^ k * Real.log (x ^ k))) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
      exact h_hx.comp ( Filter.Tendsto.inf ( ContinuousAt.tendsto ( show ContinuousAt ( fun x : ℝ => x ^ k ) 0 by exact ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inr <| by linarith ) |> fun h => h.trans <| by norm_num [ show k ≠ 0 by linarith ] ) <| Filter.tendsto_principal_principal.mpr <| by intro x hx; exact Real.rpow_pos_of_pos hx _ );
    refine h_hxk.congr' ( by filter_upwards [ self_mem_nhdsWithin ] with x hx using by rw [ Real.log_rpow hx ] ; ring );
  have := h_hx.div h_hxk;
  simp_all +decide [ division_def ];
  convert this.const_mul ( k⁻¹ ) |> Filter.Tendsto.congr' _ using 2;
  · ring;
  · filter_upwards [ self_mem_nhdsWithin ] with x hx ; by_cases hx' : Real.binEntropy x = 0 <;> by_cases hx'' : Real.binEntropy ( x ^ k ) = 0 <;> simp_all +decide [mul_assoc,
    mul_comm, mul_left_comm];
    by_cases h : Real.log x = 0 <;> simp_all +decide [ Real.rpow_sub_one, mul_comm ];
    · rcases h with ( rfl | rfl | rfl ) <;> norm_num at *;
    · grind

/-
We have $\lim_{x\to 1^-}q(x)=1/k$.
-/
lemma lemma_l1_one (k : ℝ) (hk : k > 1) :
    Filter.Tendsto (q k) (nhdsWithin 1 (Set.Iio 1)) (nhds (1 / k)) := by
  -- By definition of $q_k(x)$, we know that $q_k(x) = \frac{x^{k-1} h(x)}{h(x^k)}$ where $h(x) = -x \log x - (1-x) \log (1-x)$.
  unfold q;
  -- By definition of $h(x)$, we know that $h(x) = -x \log x - (1-x) \log (1-x)$.
  unfold Real.binEntropy;
  -- We'll use the substitution $u = 1 - x$, so as $x \to 1^-$, $u \to 0^+$.
  suffices h_subst : Filter.Tendsto (fun u => ((1 - u) ^ (k - 1) * ((1 - u) * Real.log (1 - u)⁻¹ + u * Real.log u⁻¹)) / ((1 - u) ^ k * Real.log ((1 - u) ^ k)⁻¹ + (1 - (1 - u) ^ k) * Real.log (1 - (1 - u) ^ k)⁻¹)) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / k)) by
    rw [ Metric.tendsto_nhdsWithin_nhds ] at *;
    intro ε hε; rcases h_subst ε hε with ⟨ δ, hδ, H ⟩ ; exact ⟨ δ, hδ, fun { x } hx₁ hx₂ => by convert H ( show 0 < 1 - x from by linarith [ hx₁.out ] ) ( by simpa [ dist_comm ] using hx₂ ) using 1; ring_nf ⟩ ;
  -- We'll use the fact that as $u \to 0$, $(1 - u)^k \approx 1 - ku$ and $\log(1 - u) \approx -u$.
  have h_approx : Filter.Tendsto (fun u => (1 - u) ^ (k - 1) * ((1 - u) * Real.log (1 - u)⁻¹ + u * Real.log u⁻¹) / (u * Real.log u⁻¹)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) ∧ Filter.Tendsto (fun u => ((1 - u) ^ k * Real.log ((1 - u) ^ k)⁻¹ + (1 - (1 - u) ^ k) * Real.log (1 - (1 - u) ^ k)⁻¹) / (u * Real.log u⁻¹)) (nhdsWithin 0 (Set.Ioi 0)) (nhds k) := by
    constructor;
    · -- We'll use the fact that as $u \to 0$, $(1 - u) \log(1 - u)^{-1} \approx u$ and $u \log u^{-1} \approx u$.
      have h_approx : Filter.Tendsto (fun u => ((1 - u) * Real.log (1 - u)⁻¹ + u * Real.log u⁻¹) / (u * Real.log u⁻¹)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
        -- We'll use the fact that as $u \to 0$, $(1 - u) \log(1 - u)^{-1} \approx u$ and $u \log u^{-1} \approx u$ to simplify the expression.
        have h_approx : Filter.Tendsto (fun u => (1 - u) * Real.log (1 - u)⁻¹ / (u * Real.log u⁻¹)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
          -- We'll use the fact that $\log(1 - u) \approx -u$ for $u$ close to $0$.
          have h_log_approx : Filter.Tendsto (fun u => Real.log (1 - u) / u) (nhdsWithin 0 (Set.Ioi 0)) (nhds (-1)) := by
            simpa [ div_eq_inv_mul ] using HasDerivAt.tendsto_slope_zero_right ( HasDerivAt.log ( hasDerivAt_id 0 |> HasDerivAt.const_sub 1 ) ( by norm_num ) );
          have h_log_approx : Filter.Tendsto (fun u => Real.log (1 - u) / (u * Real.log u⁻¹)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
            convert h_log_approx.div_atTop ( Real.tendsto_log_atTop.comp <| tendsto_inv_nhdsGT_zero ) using 2 ; norm_num [ div_mul_eq_div_div ];
            field_simp;
          convert h_log_approx.neg.mul ( Continuous.continuousWithinAt ( show Continuous fun u : ℝ => ( 1 - u ) by continuity ) ) using 2 <;> norm_num ; ring;
        simp_all +decide [ add_div ];
        exact le_trans ( Filter.Tendsto.add h_approx <| tendsto_const_nhds.congr' <| by filter_upwards [ ( Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, zero_lt_one ⟩ ) ] with u hu using by rw [ div_self <| mul_ne_zero hu.1.ne' <| ne_of_lt <| Real.log_neg hu.1 hu.2 ] ) <| by norm_num;
      simpa [ mul_div_assoc ] using Filter.Tendsto.mul ( ContinuousAt.continuousWithinAt ( show ContinuousAt ( fun u : ℝ => ( 1 - u ) ^ ( k - 1 ) ) 0 by exact ContinuousAt.rpow ( continuousAt_const.sub continuousAt_id ) continuousAt_const <| Or.inl <| by linarith ) ) h_approx;
    · -- We'll use the fact that as $u \to 0$, $(1 - u)^k \approx 1 - ku$ and $\log(1 - (1 - u)^k) \approx \log(ku)$.
      have h_approx : Filter.Tendsto (fun u => (1 - (1 - u) ^ k) / u) (nhdsWithin 0 (Set.Ioi 0)) (nhds k) ∧ Filter.Tendsto (fun u => Real.log (1 - (1 - u) ^ k) / Real.log u) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
        constructor;
        · simpa [ div_eq_inv_mul ] using HasDerivAt.tendsto_slope_zero_right ( HasDerivAt.const_sub 1 <| HasDerivAt.rpow ( hasDerivAt_id 0 |> HasDerivAt.const_sub 1 ) ( hasDerivAt_const _ k ) <| by norm_num );
        · -- We'll use the fact that $1 - (1 - u)^k \sim ku$ as $u \to 0$.
          have h_approx : Filter.Tendsto (fun u => (1 - (1 - u) ^ k) / u) (nhdsWithin 0 (Set.Ioi 0)) (nhds k) := by
            simpa [ div_eq_inv_mul ] using HasDerivAt.tendsto_slope_zero_right ( HasDerivAt.const_sub 1 <| HasDerivAt.rpow ( hasDerivAt_id 0 |> HasDerivAt.const_sub 1 ) ( hasDerivAt_const _ k ) <| by norm_num );
          -- We'll use the fact that $\log(1 - (1 - u)^k) \sim \log(ku)$ as $u \to 0$.
          have h_log_approx : Filter.Tendsto (fun u => Real.log (1 - (1 - u) ^ k) - Real.log u) (nhdsWithin 0 (Set.Ioi 0)) (nhds (Real.log k)) := by
            have := h_approx.log;
            exact this ( by positivity ) |> fun h => h.congr' ( by filter_upwards [ h_approx.eventually ( lt_mem_nhds <| show k > 0 by positivity ) ] with u hu using by rw [ Real.log_div ( by aesop ) ( by aesop ) ] );
          have h_log_approx : Filter.Tendsto (fun u => (Real.log (1 - (1 - u) ^ k) - Real.log u) / Real.log u) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
            have h_log_approx : Filter.Tendsto (fun u => Real.log u) (nhdsWithin 0 (Set.Ioi 0)) Filter.atBot := by
              exact Real.tendsto_log_nhdsGT_zero;
            rw [ tendsto_zero_iff_norm_tendsto_zero ];
            simpa using Filter.Tendsto.div_atTop ( Filter.Tendsto.abs ‹Filter.Tendsto ( fun u : ℝ => Real.log ( 1 - ( 1 - u ) ^ k ) - Real.log u ) ( nhdsWithin 0 ( Set.Ioi 0 ) ) ( nhds ( Real.log k ) ) › ) ( Filter.tendsto_abs_atBot_atTop.comp h_log_approx );
          simpa using h_log_approx.add_const 1 |> Filter.Tendsto.congr' ( by filter_upwards [ ( Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, zero_lt_one ⟩ ) ] with u hu using by rw [ sub_div, div_self <| ne_of_lt <| Real.log_neg hu.1 hu.2 ] ; ring );
      -- We'll use the fact that as $u \to 0$, $(1 - u)^k \approx 1 - ku$ and $\log(1 - u) \approx -u$ to simplify the expression.
      have h_approx : Filter.Tendsto (fun u => ((1 - u) ^ k * Real.log ((1 - u) ^ k)⁻¹) / (u * Real.log u⁻¹)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
        -- We'll use the fact that as $u \to 0$, $(1 - u)^k \approx 1 - ku$ and $\log(1 - u) \approx -u$ to simplify the expression. Hence, we can write:
        have h_approx : Filter.Tendsto (fun u => (1 - u) ^ k * k * Real.log (1 - u) / (u * Real.log u)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
          have h_approx : Filter.Tendsto (fun u => Real.log (1 - u) / u) (nhdsWithin 0 (Set.Ioi 0)) (nhds (-1)) := by
            simpa [ div_eq_inv_mul ] using HasDerivAt.tendsto_slope_zero_right ( HasDerivAt.log ( hasDerivAt_id 0 |> HasDerivAt.const_sub 1 ) ( by norm_num ) );
          have h_approx : Filter.Tendsto (fun u => (1 - u) ^ k * k * (Real.log (1 - u) / u) / Real.log u) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
            have h_approx : Filter.Tendsto (fun u => (1 - u) ^ k * k * (Real.log (1 - u) / u)) (nhdsWithin 0 (Set.Ioi 0)) (nhds ((1 - 0) ^ k * k * (-1))) := by
              exact Filter.Tendsto.mul ( Filter.Tendsto.mul ( Filter.Tendsto.rpow ( tendsto_const_nhds.sub <| Filter.tendsto_id.mono_left inf_le_left ) tendsto_const_nhds <| Or.inl <| by linarith ) tendsto_const_nhds ) h_approx;
            have h_approx : Filter.Tendsto (fun u => Real.log u) (nhdsWithin 0 (Set.Ioi 0)) Filter.atBot := by
              exact Real.tendsto_log_nhdsGT_zero;
            rw [ tendsto_zero_iff_norm_tendsto_zero ];
            simpa using Filter.Tendsto.div_atTop ( Filter.Tendsto.norm ‹Filter.Tendsto ( fun u : ℝ => ( 1 - u ) ^ k * k * ( Real.log ( 1 - u ) / u ) ) ( nhdsWithin 0 ( Set.Ioi 0 ) ) ( nhds ( ( 1 - 0 ) ^ k * k * -1 ) ) › ) ( Filter.tendsto_abs_atBot_atTop.comp h_approx );
          exact h_approx.congr fun x => by rw [ mul_div_assoc ] ; ring;
        refine h_approx.congr' ( by filter_upwards [ ( Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, zero_lt_one ⟩ ) ] with u hu using by simp +decide [ Real.log_rpow ( sub_pos.mpr hu.2 ), mul_assoc, mul_comm, mul_left_comm ] );
      convert h_approx.add ( ‹Filter.Tendsto ( fun u : ℝ => ( 1 - ( 1 - u ) ^ k ) / u ) ( nhdsWithin 0 ( Set.Ioi 0 ) ) ( nhds k ) ∧ Filter.Tendsto ( fun u : ℝ => Real.log ( 1 - ( 1 - u ) ^ k ) / Real.log u ) ( nhdsWithin 0 ( Set.Ioi 0 ) ) ( nhds 1 ) ›.1.mul ‹Filter.Tendsto ( fun u : ℝ => ( 1 - ( 1 - u ) ^ k ) / u ) ( nhdsWithin 0 ( Set.Ioi 0 ) ) ( nhds k ) ∧ Filter.Tendsto ( fun u : ℝ => Real.log ( 1 - ( 1 - u ) ^ k ) / Real.log u ) ( nhdsWithin 0 ( Set.Ioi 0 ) ) ( nhds 1 ) ›.2 ) using 2 <;> ring_nf;
      by_cases h : ‹ℝ› = 0 <;> simp +decide [ h, Real.log_inv ] ; ring;
  have := h_approx.1.div h_approx.2;
  exact this ( by positivity ) |> fun h => h.congr' ( by filter_upwards [ h_approx.1.eventually_ne one_ne_zero, h_approx.2.eventually_ne ( by positivity : ( k : ℝ ) ≠ 0 ) ] with u hu₁ hu₂ using by rw [ Pi.div_apply, div_div_div_cancel_right₀ ( by aesop ) ] )

/-
Given $M>0$, $0<a<1$, and a continuous function $f\colon[0,1]\to\mathbf R$ that is differentiable on $(0,1)$, suppose that $f(0)<M$, $f(a)=M$, $f(1)<M$, and $f'(x)=0$ iff $x=a$. Then $f(x)\le M$ with equality iff $x=a$.
-/
lemma lemma_l3 (M : ℝ) (a : ℝ) (f : ℝ → ℝ)
    (ha : 0 < a ∧ a < 1)
    (hf_cont : ContinuousOn f (Set.Icc 0 1))
    (h0 : f 0 < M) (ha_val : f a = M) (h1 : f 1 < M)
    (h_deriv : ∀ x ∈ Set.Ioo 0 1, deriv f x = 0 ↔ x = a) :
    ∀ x ∈ Set.Icc 0 1, f x ≤ M ∧ (f x = M ↔ x = a) := by
  -- By Fermat's theorem, $f'(c)=0$, so $c=a$.
  have h_fermat : ∀ c ∈ Set.Ioo 0 1, deriv f c = 0 → c = a := by
    aesop;
  have h_max : ∀ x ∈ Set.Icc 0 1, f x ≤ M := by
    -- By the Extreme Value Theorem, since $f$ is continuous on $[0,1]$, it attains a maximum at some $c \in [0,1]$.
    obtain ⟨c, hc⟩ : ∃ c ∈ Set.Icc 0 1, ∀ x ∈ Set.Icc 0 1, f x ≤ f c := by
      exact ( IsCompact.exists_isMaxOn ( CompactIccSpace.isCompact_Icc ) ⟨ a, Set.mem_Icc.mpr ⟨ by linarith, by linarith ⟩ ⟩ hf_cont ) |> fun ⟨ c, hc₁, hc₂ ⟩ => ⟨ c, hc₁, fun x hx => hc₂ hx ⟩;
    by_cases h_cases : c = 0 ∨ c = 1;
    · rcases h_cases with ( rfl | rfl ) <;> [ exact fun x hx => le_trans ( hc.2 x hx ) h0.le; exact fun x hx => le_trans ( hc.2 x hx ) h1.le ];
    · -- Since $c \in (0,1)$ and $f'(c) = 0$, by Fermat's theorem, we have $c = a$.
      have h_c_a : c = a := by
        exact h_fermat c ⟨ lt_of_le_of_ne hc.1.1 ( Ne.symm ( by tauto ) ), lt_of_le_of_ne hc.1.2 ( by tauto ) ⟩ ( IsLocalMax.deriv_eq_zero ( Filter.eventually_of_mem ( Icc_mem_nhds ( lt_of_le_of_ne hc.1.1 ( Ne.symm ( by tauto ) ) ) ( lt_of_le_of_ne hc.1.2 ( by tauto ) ) ) fun x hx => hc.2 x hx ) );
      grind;
  intros x hx;
  -- By the properties of the derivative, if $f(x) = M$ and $x \neq a$, then $f'(x) = 0$.
  by_cases hx_eq_a : x = a;
  · grind;
  · by_cases hx0 : x = 0 ∨ x = 1;
    · rcases hx0 with ( rfl | rfl ) <;> [ exact ⟨ by linarith, iff_of_false ( by linarith ) hx_eq_a ⟩ ; exact ⟨ by linarith, iff_of_false ( by linarith ) hx_eq_a ⟩ ];
    · exact ⟨ h_max x hx, iff_of_false ( fun h => hx_eq_a <| h_fermat x ⟨ lt_of_le_of_ne hx.1 <| Ne.symm <| by tauto, lt_of_le_of_ne hx.2 <| by tauto ⟩ <| IsLocalMax.deriv_eq_zero <| Filter.eventually_of_mem ( Ioo_mem_nhds ( lt_of_le_of_ne hx.1 <| Ne.symm <| by tauto ) ( lt_of_le_of_ne hx.2 <| by tauto ) ) fun y hy => by linarith [ h_max y <| Set.Ioo_subset_Icc_self hy ] ) hx_eq_a ⟩

/-
For $t > 0, t \ne 1$, $f(t) = \int_0^1 t^s ds$.
-/
noncomputable def f_aux (t : ℝ) : ℝ := (t - 1) / Real.log t

lemma lemma_f_integral (t : ℝ) (ht : t > 0) (ht1 : t ≠ 1) :
    f_aux t = ∫ s in (0 : ℝ)..1, t ^ s := by
  unfold f_aux;
  norm_num [ Real.rpow_def_of_pos ht ];
  rw [ intervalIntegral.integral_comp_mul_left ] <;> norm_num;
  · rw [ Real.exp_log ht, inv_mul_eq_div ];
  · exact ⟨ ht.ne', ht1, by linarith ⟩

/-
The derivative of $f(t) = \int_0^1 t^s ds$ is strictly decreasing on $(0, 1)$.
-/
noncomputable def f_int (t : ℝ) : ℝ := ∫ s in (0 : ℝ)..1, t ^ s

lemma f_int_deriv_decreasing : StrictAntiOn (deriv f_int) (Set.Ioo 0 1) := by
  -- By definition of $f_int$, we know that its derivative is $f'_int(t) = \int_0^1 s t^{s-1} ds$ for $t \in (0, 1)$.
  have h_deriv : ∀ t ∈ Set.Ioo (0 : ℝ) 1, deriv (fun t => ∫ s in (0 : ℝ)..1, t^s) t = ∫ s in (0 : ℝ)..1, s * t^(s - 1) := by
    intro t ht;
    refine' HasDerivAt.deriv _;
    convert HasDerivAt.congr_of_eventuallyEq _ ?_ using 1;
    exact fun t => ( t - 1 ) / Real.log t;
    · convert HasDerivAt.div ( HasDerivAt.sub ( hasDerivAt_id t ) ( hasDerivAt_const _ _ ) ) ( Real.hasDerivAt_log ht.1.ne' ) ( ne_of_lt ( Real.log_neg ht.1 ht.2 ) ) using 1;
      rw [ intervalIntegral.integral_eq_sub_of_hasDerivAt ];
      rotate_right;
      use fun x => ( x * t ^ ( x - 1 ) ) / Real.log t - t ^ ( x - 1 ) / Real.log t ^ 2;
      · norm_num [ Real.rpow_neg_one ] ; ring_nf;
        simp +decide [ sq, mul_assoc, ht.1.ne' ];
        norm_num [ show Real.log t ≠ 0 by linarith [ Real.log_le_sub_one_of_pos ht.1, ht.2 ] ];
      · intro x hx; convert HasDerivAt.sub ( HasDerivAt.div_const ( HasDerivAt.mul ( hasDerivAt_id x ) ( HasDerivAt.rpow ( hasDerivAt_const _ _ ) ( hasDerivAt_id x |> HasDerivAt.sub <| hasDerivAt_const _ _ ) _ ) ) _ ) ( HasDerivAt.div_const ( HasDerivAt.rpow ( hasDerivAt_const _ _ ) ( hasDerivAt_id x |> HasDerivAt.sub <| hasDerivAt_const _ _ ) _ ) _ ) using 1 <;> norm_num [ ht.1.ne', ht.2.ne' ] ; ring_nf;
        · by_cases h : Real.log t = 0 <;> simp_all +decide [ sq, mul_assoc ];
          rcases h with ( rfl | rfl | rfl ) <;> norm_num at *;
        · exact ht.1;
        · linarith [ ht.1, ht.2 ];
      · exact Continuous.intervalIntegrable ( by exact Continuous.mul continuous_id ( Continuous.rpow continuous_const ( continuous_id.sub continuous_const ) <| by continuity ) ) _ _;
    · filter_upwards [ Ioo_mem_nhds ht.1 ht.2 ] with x hx;
      norm_num [ Real.rpow_def_of_pos hx.1 ];
      rw [ intervalIntegral.integral_comp_mul_left ] <;> norm_num [ hx.1.ne', hx.2.ne ];
      · rw [ Real.exp_log hx.1, inv_mul_eq_div ];
      · linarith [ hx.1, hx.2 ];
  -- By definition of $f_int$, we know that its derivative is $f'_int(t) = \int_0^1 s t^{s-1} ds$ for $t \in (0, 1)$. We need to show that this derivative is strictly decreasing.
  have h_deriv_decreasing : ∀ t1 t2 : ℝ, 0 < t1 → t1 < t2 → t2 < 1 → ∫ s in (0 : ℝ)..1, s * t1^(s - 1) > ∫ s in (0 : ℝ)..1, s * t2^(s - 1) := by
    intros t1 t2 ht1 ht2 ht2_lt_1
    have h_integral_lt : ∀ s ∈ Set.Ioo (0 : ℝ) 1, s * t1^(s - 1) > s * t2^(s - 1) := by
      exact fun s hs => mul_lt_mul_of_pos_left ( by rw [ Real.rpow_lt_rpow_iff_of_neg ] <;> linarith [ hs.1, hs.2 ] ) hs.1;
    apply lt_of_sub_pos;
    rw [ ← intervalIntegral.integral_sub ];
    · rw [ intervalIntegral.integral_of_le zero_le_one, MeasureTheory.integral_Ioc_eq_integral_Ioo ];
      rw [ MeasureTheory.integral_pos_iff_support_of_nonneg_ae ];
      · simp +zetaDelta at *;
        exact lt_of_lt_of_le ( by norm_num ) ( MeasureTheory.measure_mono <| show Set.Ioo 0 1 ⊆ ( Function.support fun t : ℝ => t * t1 ^ ( t - 1 ) - t * t2 ^ ( t - 1 ) ) ∩ Set.Ioo 0 1 from fun x hx => ⟨ ne_of_gt <| sub_pos.mpr <| h_integral_lt x hx.1 hx.2, hx ⟩ );
      · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioo ] with s hs using sub_nonneg_of_le <| le_of_lt <| h_integral_lt s hs;
      · exact ContinuousOn.integrableOn_Icc ( by exact continuousOn_of_forall_continuousAt fun x hx => by exact ContinuousAt.sub ( ContinuousAt.mul continuousAt_id <| ContinuousAt.rpow continuousAt_const ( continuousAt_id.sub continuousAt_const ) <| Or.inl <| by linarith ) <| ContinuousAt.mul continuousAt_id <| ContinuousAt.rpow continuousAt_const ( continuousAt_id.sub continuousAt_const ) <| Or.inl <| by linarith ) |> fun h => h.mono_set <| Set.Ioo_subset_Icc_self;
    · exact ContinuousOn.intervalIntegrable ( by exact continuousOn_of_forall_continuousAt fun x hx => by exact ContinuousAt.mul continuousAt_id <| ContinuousAt.rpow continuousAt_const ( continuousAt_id.sub continuousAt_const ) <| Or.inl <| by linarith );
    · exact ContinuousOn.intervalIntegrable ( by exact continuousOn_of_forall_continuousAt fun x hx => by exact ContinuousAt.mul continuousAt_id <| ContinuousAt.rpow continuousAt_const ( continuousAt_id.sub continuousAt_const ) <| Or.inl <| by linarith );
  intros t1 ht1 t2 ht2 hltop;
  convert h_deriv_decreasing t1 t2 ht1.1 hltop ht2.2 |> lt_of_lt_of_le <| le_rfl using 1 <;> aesop

/-
For $x \in (0, 1)$, $1/G(x) = f(x) + f(1-x)$ where $f(t) = \int_0^1 t^s ds$.
-/
noncomputable def G (x : ℝ) : ℝ := Real.log x * Real.log (1 - x) / Real.binEntropy x

lemma one_div_G_eq (x : ℝ) (hx : 0 < x ∧ x < 1) :
    1 / G x = f_int x + f_int (1 - x) := by
  unfold G f_int;
  norm_num [ Real.rpow_def_of_pos hx.1, Real.rpow_def_of_pos ( sub_pos.2 hx.2 ), mul_comm ];
  rw [ intervalIntegral.integral_comp_mul_right, intervalIntegral.integral_comp_mul_right ] <;> norm_num [ Real.log_pow, hx.1.ne', hx.2.ne' ];
  · rw [ Real.exp_log hx.1, Real.exp_log ( by linarith ) ] ; unfold Real.binEntropy ; ring_nf;
    rw [ Real.log_inv, Real.log_inv ] ; ring_nf;
    simpa [ show Real.log x ≠ 0 from ne_of_lt ( Real.log_neg hx.1 hx.2 ), show Real.log ( 1 - x ) ≠ 0 from ne_of_lt ( Real.log_neg ( by linarith ) ( by linarith ) ) ] using by ring;
  · constructor <;> linarith;
  · constructor <;> linarith

/-
For $x \in (0, 1)$, $1/G(x) = f(x) + f(1-x)$ where $f(t) = \int_0^1 t^s ds$.
-/
noncomputable def BoppanaG (x : ℝ) : ℝ := Real.log x * Real.log (1 - x) / Real.binEntropy x

lemma one_div_BoppanaG_eq (x : ℝ) (hx : 0 < x ∧ x < 1) :
    1 / BoppanaG x = f_int x + f_int (1 - x) := by
  convert one_div_G_eq x hx using 1

/-
$1/BoppanaG$ is strictly increasing on $(0, 1/2)$.
-/
lemma one_div_BoppanaG_strictMonoOn : StrictMonoOn (fun x => 1 / BoppanaG x) (Set.Ioo 0 (1 / 2)) := by
  -- The derivative of $1/BoppanaG$ is $f_int'(x) - f_int'(1-x)$.
  have h_deriv : ∀ x ∈ Set.Ioo 0 (1 / 2), deriv (fun x => 1 / BoppanaG x) x = deriv f_int x - deriv f_int (1 - x) := by
    intro x hx;
    rw [ show deriv ( fun x => 1 / BoppanaG x ) x = deriv ( fun x => f_int x + f_int ( 1 - x ) ) x by exact Filter.EventuallyEq.deriv_eq <| Filter.eventuallyEq_of_mem ( Ioo_mem_nhds hx.1 hx.2 ) fun y hy => one_div_BoppanaG_eq y ⟨ hy.1, by linarith [ hy.2 ] ⟩ ];
    convert HasDerivAt.deriv ( HasDerivAt.add ( hasDerivAt_deriv_iff.mpr ?_ ) ( HasDerivAt.comp x ( hasDerivAt_deriv_iff.mpr ?_ ) ( hasDerivAt_id' x |> HasDerivAt.const_sub 1 ) ) ) using 1 <;> norm_num;
    congr! 1;
    exact (Set.eqOn_univ (fun x ↦ f_int x + f_int (1 - x)) (f_int + f_int ∘ fun x ↦ 1 - x)).mp fun ⦃x⦄ a ↦
    congrArg (HAdd.hAdd (f_int x)) (congrFun rfl (1 - x));
    · ring;
    · -- The integral of $t^s$ with respect to $s$ is $\frac{t^s}{\log t}$, so $f_int(x) = \frac{x - 1}{\log x}$.
      have h_f_int : ∀ x ∈ Set.Ioo 0 1, f_int x = (x - 1) / Real.log x := by
        intro x hx; rw [ f_int ] ; rw [ intervalIntegral.integral_congr fun s hs => by rw [ Real.rpow_def_of_pos hx.1 ] ] ; norm_num [ div_eq_mul_inv, intervalIntegral.integral_comp_mul_left, hx.1.ne', hx.2.ne' ] ;
        rw [ intervalIntegral.integral_comp_mul_left ] <;> norm_num [ hx.1.ne', hx.2.ne' ];
        · rw [ Real.exp_log hx.1, mul_comm ];
        · constructor <;> linarith [ hx.1, hx.2 ];
      exact DifferentiableAt.congr_of_eventuallyEq ( show DifferentiableAt ℝ ( fun x => ( x - 1 ) / Real.log x ) x from DifferentiableAt.div ( differentiableAt_id.sub_const _ ) ( Real.differentiableAt_log hx.1.ne' ) ( ne_of_lt ( Real.log_neg hx.1 ( by linarith [ hx.2 ] ) ) ) ) ( Filter.eventuallyEq_of_mem ( Ioo_mem_nhds hx.1 ( by linarith [ hx.2 ] ) ) fun y hy => h_f_int y hy );
    · have h_diff : ∀ t ∈ Set.Ioo 0 1, DifferentiableAt ℝ f_int t := by
        intro t ht;
        have h_diff : DifferentiableAt ℝ (fun t => ∫ s in (0 : ℝ)..1, t ^ s) t := by
          have h_int : ∀ t ∈ Set.Ioo 0 1, ∫ s in (0 : ℝ)..1, t ^ s = (t - 1) / Real.log t := by
            intro t ht; norm_num [ Real.rpow_def_of_pos ht.1 ];
            rw [ intervalIntegral.integral_comp_mul_left ] <;> norm_num [ ht.1.ne', ht.2.ne ];
            · rw [ Real.exp_log ht.1, inv_mul_eq_div ];
            · linarith [ ht.1, ht.2 ]
          exact DifferentiableAt.congr_of_eventuallyEq ( show DifferentiableAt ℝ ( fun t => ( t - 1 ) / Real.log t ) t from DifferentiableAt.div ( differentiableAt_id.sub_const _ ) ( Real.differentiableAt_log ht.1.ne' ) ( ne_of_lt ( Real.log_neg ht.1 ht.2 ) ) ) ( Filter.eventuallyEq_of_mem ( Ioo_mem_nhds ht.1 ht.2 ) fun x hx => h_int x hx );
        exact h_diff;
      exact h_diff _ ⟨ by linarith [ hx.1, hx.2 ], by linarith [ hx.1, hx.2 ] ⟩;
  -- Since $f_int'$ is strictly decreasing on $(0, 1)$, $f_int'(x) > f_int'(1-x)$ for $x \in (0, 1/2)$.
  have h_deriv_pos : ∀ x ∈ Set.Ioo 0 (1 / 2), deriv f_int x > deriv f_int (1 - x) := by
    exact fun x hx => f_int_deriv_decreasing ⟨ by linarith [ hx.1, hx.2 ], by linarith [ hx.1, hx.2 ] ⟩ ⟨ by linarith [ hx.1, hx.2 ], by linarith [ hx.1, hx.2 ] ⟩ ( by linarith [ hx.1, hx.2 ] );
  intro x hx y hy hxy;
  -- By the Mean Value Theorem, there exists some $c \in (x, y)$ such that $f'(c) = (f(y) - f(x)) / (y - x)$.
  obtain ⟨c, hc⟩ : ∃ c ∈ Set.Ioo x y, deriv (fun x => 1 / BoppanaG x) c = (1 / BoppanaG y - 1 / BoppanaG x) / (y - x) := by
    apply_rules [ exists_deriv_eq_slope ];
    · refine' continuousOn_of_forall_continuousAt fun z hz => ContinuousAt.div continuousAt_const _ _;
      · refine' ContinuousAt.div _ _ _ <;> norm_num;
        · exact ContinuousAt.mul ( Real.continuousAt_log ( by linarith [ hx.1, hy.1, hz.1 ] ) ) ( ContinuousAt.log ( continuousAt_const.sub continuousAt_id ) ( by linarith [ hx.2, hy.2, hz.2 ] ) );
        · refine' ContinuousAt.add _ _;
          · exact ContinuousAt.mul continuousAt_id ( ContinuousAt.log ( continuousAt_id.inv₀ <| ne_of_gt <| lt_of_lt_of_le hx.1 hz.1 ) <| ne_of_gt <| inv_pos.mpr <| lt_of_lt_of_le hx.1 hz.1 );
          · exact ContinuousAt.mul ( continuousAt_const.sub continuousAt_id ) ( ContinuousAt.log ( ContinuousAt.inv₀ ( continuousAt_const.sub continuousAt_id ) ( by linarith [ hx.1, hx.2, hy.1, hy.2, hz.1, hz.2 ] ) ) ( by exact ne_of_gt ( inv_pos.mpr ( by linarith [ hx.1, hx.2, hy.1, hy.2, hz.1, hz.2 ] ) ) ) );
        · norm_num [ Real.binEntropy ];
          nlinarith [ hx.1, hx.2, hy.1, hy.2, hz.1, hz.2, Real.log_le_sub_one_of_pos ( show 0 < z by linarith [ hx.1, hz.1 ] ), Real.log_le_sub_one_of_pos ( show 0 < 1 - z by linarith [ hy.2, hz.2 ] ) ];
      · unfold BoppanaG;
        norm_num [ Real.binEntropy ];
        exact ⟨ ⟨ ⟨ by linarith [ hx.1, hy.1, hz.1 ], by linarith [ hx.2, hy.2, hz.2 ], by linarith [ hx.1, hy.1, hz.1 ] ⟩, by linarith [ hx.2, hy.2, hz.2 ], by linarith [ hx.1, hy.1, hz.1 ], by linarith [ hx.2, hy.2, hz.2 ] ⟩, by nlinarith [ hx.1, hy.1, hz.1, hx.2, hy.2, hz.2, Real.log_le_sub_one_of_pos ( by linarith [ hx.1, hy.1, hz.1 ] : 0 < z ), Real.log_le_sub_one_of_pos ( by linarith [ hx.2, hy.2, hz.2 ] : 0 < 1 - z ) ] ⟩;
    · exact fun z hz => DifferentiableAt.differentiableWithinAt ( by exact differentiableAt_of_deriv_ne_zero ( by rw [ h_deriv z ⟨ by linarith [ hx.1, hy.1, hz.1 ], by linarith [ hx.2, hy.2, hz.2 ] ⟩ ] ; linarith [ h_deriv_pos z ⟨ by linarith [ hx.1, hy.1, hz.1 ], by linarith [ hx.2, hy.2, hz.2 ] ⟩ ] ) );
  have := h_deriv c ⟨ by linarith [ hc.1.1, hx.1 ], by linarith [ hc.1.2, hy.2 ] ⟩ ; have := h_deriv_pos c ⟨ by linarith [ hc.1.1, hx.1 ], by linarith [ hc.1.2, hy.2 ] ⟩ ; rw [ eq_div_iff ] at hc <;> nlinarith;

/-
`BoppanaG` is strictly decreasing on $(0, 1/2)$.
-/
lemma BoppanaG_strictAntiOn_Ioo : StrictAntiOn BoppanaG (Set.Ioo 0 (1 / 2)) := by
  -- Since $BoppanaG(x) > 0$ for $x \in (0, 1/2)$, the function $y \mapsto 1/y$ is strictly decreasing on the range of $BoppanaG$.
  have h_BoppanaG_pos : ∀ x : ℝ, 0 < x ∧ x < 1 / 2 → 0 < BoppanaG x := by
    unfold BoppanaG;
    norm_num [ Real.binEntropy ];
    exact fun x hx₁ hx₂ => div_pos ( mul_pos_of_neg_of_neg ( Real.log_neg hx₁ ( by linarith ) ) ( Real.log_neg ( by linarith ) ( by linarith ) ) ) ( by nlinarith [ Real.log_le_sub_one_of_pos hx₁, Real.log_le_sub_one_of_pos ( by linarith : 0 < 1 - x ) ] );
  intro x hx y hy hxy;
  have := one_div_BoppanaG_strictMonoOn hx hy hxy; rw [ div_lt_div_iff₀ ] at this <;> linarith [ h_BoppanaG_pos x hx, h_BoppanaG_pos y hy ] ;

/-
Suppose $x^k=1-x$. Then $x=1/(1+\alpha_k)$.
-/
lemma lemma_l5 (k : ℝ) (hk : k > 1) (x : ℝ) (hx : 0 < x ∧ x < 1) (h_eq : x ^ k = 1 - x) :
    x = 1 / (1 + alpha k) := by
  -- By definition of $alpha_k$, we know that $alpha_k = \frac{1 - x}{x}$.
  have h_alpha : alpha k = (1 - x) / x := by
    -- By definition of $alpha_k$, we know that $alpha_k$ is the unique solution to $x(1+x)^{k-1}=1$ in $(0, 1)$.
    have h_alpha_unique : ∀ x > 0, x * (1 + x) ^ (k - 1) = 1 → x = alpha k := by
      intro x hx_pos hx_eq
      have h_unique : ∀ y > 0, y * (1 + y) ^ (k - 1) = 1 → y = x := by
        intros y hy_pos hy_eq
        have h_unique : StrictMonoOn (fun x : ℝ => x * (1 + x) ^ (k - 1)) (Set.Ioi 0) := by
          exact fun x hx y hy hxy => mul_lt_mul'' hxy ( Real.rpow_lt_rpow ( by linarith [ hx.out ] ) ( by linarith [ hx.out, hy.out ] ) ( by linarith ) ) ( by linarith [ hx.out, hy.out ] ) ( by exact Real.rpow_nonneg ( by linarith [ hx.out, hy.out ] ) _ );
        exact StrictMonoOn.injOn h_unique hy_pos hx_pos <| by linarith;
      unfold alpha;
      have := Classical.choose_spec ( show ∃ x : ℝ, x > 0 ∧ x * ( 1 + x ) ^ ( k - 1 ) = 1 from ⟨ x, hx_pos, hx_eq ⟩ ) ; specialize h_unique _ this.1 this.2; aesop;
    rw [ ← h_alpha_unique ( ( 1 - x ) / x ) ( div_pos ( by linarith ) hx.1 ) ];
    rw [ show ( 1 + ( 1 - x ) / x ) = ( 1 / x ) by rw [ add_div' ] <;> norm_num ; linarith ];
    rw [ Real.div_rpow ] <;> norm_num <;> try linarith;
    rw [ ← h_eq, Real.rpow_sub hx.1, Real.rpow_one ] ; ring_nf ; norm_num [ hx.1.ne' ];
    nlinarith [ mul_inv_cancel₀ hx.1.ne', mul_inv_cancel₀ ( ne_of_gt ( Real.rpow_pos_of_pos hx.1 k ) ) ];
  grind

/-
We have $\lim_{x\to 0^+}q(x)=\lim_{x\to1^-}q(x)=1/k$.
-/
lemma lemma_l1 (k : ℝ) (hk : k > 1) :
    Filter.Tendsto (q k) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / k)) ∧
    Filter.Tendsto (q k) (nhdsWithin 1 (Set.Iio 1)) (nhds (1 / k)) := by
  exact ⟨lemma_l1_zero k hk, lemma_l1_one k hk⟩

/-
$BoppanaG(1-x)=BoppanaG(x)$.
-/
lemma BoppanaG_symm (x : ℝ) : BoppanaG (1 - x) = BoppanaG x := by
  unfold BoppanaG;
  unfold Real.binEntropy; ring_nf;

/-
`BoppanaG` is strictly decreasing on $(0, 1/2]$.
-/
lemma BoppanaG_strictAntiOn_Ioc : StrictAntiOn BoppanaG (Set.Ioc 0 (1 / 2)) := by
  -- We already know `BoppanaG` is strictly decreasing on $(0, 1/2)$.
  have h_l6 : StrictAntiOn BoppanaG (Set.Ioo 0 (1 / 2)) := by
    exact BoppanaG_strictAntiOn_Ioo;
  -- Since `BoppanaG` is continuous at $1/2$, the strict decrease extends to $(0, 1/2]$.
  have h_cont : Filter.Tendsto (fun x => BoppanaG x) (nhdsWithin (1 / 2) (Set.Iio (1 / 2))) (nhds (BoppanaG (1 / 2))) := by
    refine' Filter.Tendsto.mono_left _ nhdsWithin_le_nhds;
    refine' ContinuousAt.div _ _ _ <;> norm_num [ Real.binEntropy ];
    · exact ContinuousAt.mul ( Real.continuousAt_log ( by norm_num ) ) ( ContinuousAt.log ( continuousAt_const.sub continuousAt_id ) ( by norm_num ) );
    · refine' ContinuousAt.add _ _ <;> norm_num [ Real.binEntropy ];
      · exact ContinuousAt.neg ( ContinuousAt.mul continuousAt_id ( Real.continuousAt_log ( by norm_num ) ) );
      · exact ContinuousAt.neg ( ContinuousAt.mul ( continuousAt_const.sub continuousAt_id ) ( ContinuousAt.log ( continuousAt_const.sub continuousAt_id ) ( by norm_num ) ) );
  -- For any $x \in (0, 1/2)$, $BoppanaG(x) > \lim_{t \to 1/2^-} BoppanaG(t) = BoppanaG(1/2)$.
  have h_lim : ∀ x ∈ Set.Ioo 0 (1 / 2), BoppanaG x > BoppanaG (1 / 2) := by
    intro x hx;
    refine' lt_of_le_of_lt _ ( h_l6 ⟨ hx.1, hx.2 ⟩ ⟨ show 0 < ( x + 1 / 2 ) / 2 by linarith [ hx.1 ], show ( x + 1 / 2 ) / 2 < 1 / 2 by linarith [ hx.2 ] ⟩ ( show x < ( x + 1 / 2 ) / 2 by linarith [ hx.1, hx.2 ] ) );
    refine' le_of_tendsto h_cont _;
    filter_upwards [ Ioo_mem_nhdsLT ( show ( x + 1 / 2 ) / 2 < 1 / 2 by linarith [ hx.2 ] ) ] with y hy using h_l6.le_iff_ge ( by constructor <;> linarith [ hy.1, hy.2, hx.1, hx.2 ] ) ( by constructor <;> linarith [ hy.1, hy.2, hx.1, hx.2 ] ) |>.2 hy.1.le;
  intro x hx y hy hxy;
  cases eq_or_lt_of_le hx.2 <;> cases eq_or_lt_of_le hy.2 <;> first | linarith | aesop

/-
$BoppanaG(x)=BoppanaG(y) \iff x=y \lor x=1-y$ for $x,y \in (0,1)$.
-/
lemma BoppanaG_eq_iff (x y : ℝ) (hx : 0 < x ∧ x < 1) (hy : 0 < y ∧ y < 1) :
    BoppanaG x = BoppanaG y ↔ x = y ∨ x = 1 - y := by
  constructor <;> intro hxy;
  · -- Assume w.l.o.g. $x \le 1/2$.
    suffices h_wlog : ∀ {x y : ℝ}, 0 < x → x < 1 → 0 < y → y < 1 → x ≤ 1 / 2 → BoppanaG x = BoppanaG y → x = y ∨ x = 1 - y by
      by_cases hx2 : x ≤ 1 / 2;
      · exact h_wlog hx.1 hx.2 hy.1 hy.2 hx2 hxy;
      · contrapose! h_wlog;
        use 1 - x, 1 - y;
        exact ⟨ by linarith, by linarith, by linarith, by linarith, by linarith, by simpa [ BoppanaG_symm ] using hxy, by aesop ⟩;
    intros x y hx hy hx' hy' hxy h_eq
    by_cases hy'' : y ≤ 1 / 2;
    · -- Since $BoppanaG$ is strictly decreasing on $(0, 1/2]$, it is injective there.
      have h_inj : StrictAntiOn BoppanaG (Set.Ioc 0 (1 / 2)) := by
        exact BoppanaG_strictAntiOn_Ioc;
      exact Or.inl <| StrictAntiOn.injOn h_inj ⟨ hx, hxy ⟩ ⟨ hx', hy'' ⟩ h_eq;
    · -- Since $y > 1/2$, we have $1 - y \in (0, 1/2)$. By the symmetry of $BoppanaG$, we have $BoppanaG(y) = BoppanaG(1 - y)$.
      have h_symm : BoppanaG y = BoppanaG (1 - y) := by
        exact Eq.symm (BoppanaG_symm y);
      have h_inj : StrictAntiOn BoppanaG (Set.Ioc 0 (1 / 2)) := by
        exact BoppanaG_strictAntiOn_Ioc;
      exact Or.inr <| StrictAntiOn.injOn h_inj ⟨ by linarith, by linarith ⟩ ⟨ by linarith, by linarith ⟩ <| by linarith;
  · cases hxy <;> simp +decide [ *, BoppanaG_symm ]

/-
$q'(x)=0 \iff BoppanaG(x)=BoppanaG(x^k)$ for $x \in (0, 1)$.
-/
lemma q_deriv_eq_zero_iff (k : ℝ) (hk : k > 1) (x : ℝ) (hx : 0 < x ∧ x < 1) :
    deriv (q k) x = 0 ↔ BoppanaG x = BoppanaG (x ^ k) := by
  -- By definition of $q$, we know that $q'(x)=0 \iff ((k-1)h(x) + xh'(x))h(x^k) = kx^k h(x) h'(x^k)$.
  have h_eq : deriv (q k) x = 0 ↔ ((k - 1) * Real.binEntropy x + x * deriv Real.binEntropy x) * Real.binEntropy (x ^ k) = k * x ^ k * Real.binEntropy x * deriv Real.binEntropy (x ^ k) := by
    have h_eq : deriv (q k) x = ((k - 1) * x ^ (k - 2) * Real.binEntropy x + x ^ (k - 1) * deriv Real.binEntropy x) * Real.binEntropy (x ^ k) / Real.binEntropy (x ^ k) ^ 2 - x ^ (k - 1) * Real.binEntropy x * k * x ^ (k - 1) * deriv Real.binEntropy (x ^ k) / Real.binEntropy (x ^ k) ^ 2 := by
      convert HasDerivAt.deriv ( HasDerivAt.div ( HasDerivAt.mul ( HasDerivAt.rpow ( hasDerivAt_id x ) ( hasDerivAt_const _ _ ) _ ) ( show HasDerivAt ( fun x => Real.binEntropy x ) _ _ from hasDerivAt_deriv_iff.mpr ?_ ) ) ( show HasDerivAt ( fun x => Real.binEntropy ( x ^ k ) ) _ _ from HasDerivAt.comp x ( show HasDerivAt ( fun x => Real.binEntropy x ) _ _ from hasDerivAt_deriv_iff.mpr ?_ ) ( HasDerivAt.rpow ( hasDerivAt_id x ) ( hasDerivAt_const _ _ ) _ ) ) _ ) using 1 <;> norm_num;
      all_goals norm_num [ Real.binEntropy ];
      any_goals linarith;
      · unfold Real.binEntropy; norm_num [ sub_mul ] ; ring_nf;
      · exact DifferentiableAt.add ( DifferentiableAt.neg ( differentiableAt_id.mul ( Real.differentiableAt_log hx.1.ne' ) ) ) ( DifferentiableAt.neg ( DifferentiableAt.mul ( differentiableAt_id.const_sub _ ) ( DifferentiableAt.log ( differentiableAt_id.const_sub _ ) ( by linarith ) ) ) );
      · exact DifferentiableAt.add ( DifferentiableAt.neg ( differentiableAt_id.mul ( Real.differentiableAt_log ( by exact ne_of_gt ( Real.rpow_pos_of_pos hx.1 _ ) ) ) ) ) ( DifferentiableAt.neg ( DifferentiableAt.mul ( differentiableAt_id.const_sub _ ) ( DifferentiableAt.log ( differentiableAt_id.const_sub _ ) ( by exact ne_of_gt ( sub_pos.mpr ( Real.rpow_lt_one hx.1.le hx.2 ( by positivity ) ) ) ) ) ) );
      · nlinarith [ show x ^ k > 0 by exact Real.rpow_pos_of_pos hx.1 _, show x ^ k < 1 by exact Real.rpow_lt_one hx.1.le hx.2 ( by linarith ), Real.log_le_sub_one_of_pos ( show 0 < x ^ k by exact Real.rpow_pos_of_pos hx.1 _ ), Real.log_le_sub_one_of_pos ( show 0 < 1 - x ^ k by exact sub_pos.mpr ( Real.rpow_lt_one hx.1.le hx.2 ( by linarith ) ) ) ];
    rw [ h_eq, div_sub_div_same, div_eq_iff ];
    · rw [ show k - 2 = k - 1 - 1 by ring, Real.rpow_sub_one hx.1.ne', Real.rpow_sub_one hx.1.ne' ] ; ring_nf;
      field_simp;
      rw [ div_eq_iff ( pow_ne_zero 2 hx.1.ne' ) ] ; constructor <;> intro <;> nlinarith [ Real.rpow_pos_of_pos hx.1 k ] ;
    · simp +zetaDelta at *;
      unfold Real.binEntropy;
      rw [ Real.log_inv, Real.log_inv ];
      nlinarith [ Real.log_le_sub_one_of_pos ( show 0 < x ^ k by exact Real.rpow_pos_of_pos hx.1 _ ), Real.log_le_sub_one_of_pos ( show 0 < 1 - x ^ k by exact sub_pos.mpr ( Real.rpow_lt_one hx.1.le hx.2 ( by linarith ) ) ), Real.rpow_pos_of_pos hx.1 k, Real.rpow_lt_one hx.1.le hx.2 ( by linarith : 0 < k ) ];
  -- Using $xh'(x) = h(x) + \log(1-x)$ and $x^k h'(x^k) = h(x^k) + \log(1-x^k)$, we get
  have h_log : deriv Real.binEntropy x = (Real.binEntropy x + Real.log (1 - x)) / x ∧ deriv Real.binEntropy (x ^ k) = (Real.binEntropy (x ^ k) + Real.log (1 - x ^ k)) / (x ^ k) := by
    have h_log : ∀ x ∈ Set.Ioo 0 1, deriv Real.binEntropy x = (Real.binEntropy x + Real.log (1 - x)) / x := by
      unfold Real.binEntropy;
      intro x hx; norm_num [ Real.log_inv, sub_mul, hx.1.ne', hx.2.ne', ne_of_gt hx.1, ne_of_gt ( sub_pos.mpr hx.2 ) ] ; ring_nf;
      convert HasDerivAt.deriv ( HasDerivAt.add ( HasDerivAt.neg ( HasDerivAt.mul ( hasDerivAt_id x ) ( Real.hasDerivAt_log hx.1.ne' ) ) ) ( HasDerivAt.sub ( HasDerivAt.mul ( hasDerivAt_id x ) ( HasDerivAt.log ( hasDerivAt_id x |> HasDerivAt.const_sub 1 ) ( by linarith [ hx.1, hx.2 ] : ( 1 - x ) ≠ 0 ) ) ) ( HasDerivAt.log ( hasDerivAt_id x |> HasDerivAt.const_sub 1 ) ( by linarith [ hx.1, hx.2 ] : ( 1 - x ) ≠ 0 ) ) ) ) using 1 ; ring_nf!;
      nlinarith [ hx.1, hx.2, mul_inv_cancel₀ hx.1.ne', mul_inv_cancel₀ ( by linarith [ hx.1, hx.2 ] : ( 1 - x ) ≠ 0 ), Real.log_le_sub_one_of_pos hx.1, Real.log_le_sub_one_of_pos ( by linarith [ hx.1, hx.2 ] : 0 < 1 - x ) ];
    exact ⟨ h_log x hx, h_log ( x ^ k ) ⟨ Real.rpow_pos_of_pos hx.1 _, Real.rpow_lt_one hx.1.le hx.2 ( by positivity ) ⟩ ⟩;
  simp_all +decide [ mul_div_cancel₀, ne_of_gt ];
  norm_num [ BoppanaG, mul_assoc, mul_div_cancel₀ _ ( ne_of_gt ( Real.rpow_pos_of_pos hx.1 k ) ) ];
  by_cases h : Real.binEntropy x = 0 <;> by_cases h' : Real.binEntropy ( x ^ k ) = 0 <;> simp_all +decide [ Real.log_rpow hx.1, mul_assoc, ne_of_gt ( Real.rpow_pos_of_pos hx.1 _ ) ];
  · norm_num [ Real.binEntropy ] at *;
    exact absurd h ( by nlinarith [ Real.log_le_sub_one_of_pos hx.1, Real.log_le_sub_one_of_pos ( by linarith : 0 < 1 - x ) ] );
  · unfold Real.binEntropy at *;
    simp_all +decide [ Real.log_inv, Real.rpow_def_of_pos hx.1 ];
    contrapose! h';
    exact ne_of_gt ( add_pos_of_pos_of_nonneg ( neg_pos_of_neg ( mul_neg_of_pos_of_neg ( Real.exp_pos _ ) ( mul_neg_of_neg_of_pos ( Real.log_neg hx.1 hx.2 ) ( by linarith ) ) ) ) ( neg_nonneg_of_nonpos ( mul_nonpos_of_nonneg_of_nonpos ( sub_nonneg.mpr ( Real.exp_le_one_iff.mpr ( by nlinarith [ Real.log_le_sub_one_of_pos hx.1 ] ) ) ) ( Real.log_nonpos ( sub_nonneg.mpr ( Real.exp_le_one_iff.mpr ( by nlinarith [ Real.log_le_sub_one_of_pos hx.1 ] ) ) ) ( sub_le_self _ ( Real.exp_nonneg _ ) ) ) ) ) );
  · field_simp;
    rw [ eq_div_iff ( ne_of_gt ( Real.rpow_pos_of_pos hx.1 _ ) ) ] ; ring_nf;
    constructor <;> intro <;> nlinarith [ Real.log_le_sub_one_of_pos hx.1, Real.log_pos ( show 1 < k by linarith ), Real.rpow_pos_of_pos hx.1 k ]

/-
$q(1/(1+\alpha_k)) = \alpha_k$.
-/
lemma lemma_q_alpha (k : ℝ) (hk : k > 1) :
    q k (1 / (1 + alpha k)) = alpha k := by
  unfold q
  have hα : 0 < alpha k := alpha_pos k hk
  have h1α : 0 < 1 + alpha k := by linarith
  have h_alpha : alpha k = 1 / (1 + alpha k) ^ (k - 1) := by
    refine (eq_div_iff ?_).2 ?_
    · exact (Real.rpow_pos_of_pos h1α _).ne'
    · simpa [mul_comm] using (alpha_spec k hk).2
  have h_alpha_inv : (1 / (1 + alpha k)) ^ (k - 1) = alpha k := by
    rw [Real.div_rpow]
    · simpa [Real.one_rpow] using h_alpha.symm
    · norm_num
    · exact h1α.le
  rw [show (1 / (1 + alpha k)) ^ k = (1 / (1 + alpha k)) ^ (k - 1) * (1 / (1 + alpha k)) by
        rw [← Real.rpow_add_one (one_div_ne_zero (by linarith))]
        ring_nf, h_alpha_inv]
  field_simp
  rw [div_eq_iff]
  · unfold Real.binEntropy
    field_simp
    grind
  · have hx0 : 0 < alpha k / (1 + alpha k) := by
      exact div_pos hα h1α
    have hx1 : alpha k / (1 + alpha k) < 1 := by
      exact (div_lt_one h1α).2 (by linarith)
    exact (Real.binEntropy_pos hx0 hx1).ne'

/-
Let $k>1$ be real. Then $\alpha_k h(x^k)\ge x^{k-1}h(x)$ for $0\le x\le1$.
-/
theorem generalized_boppana (k : ℝ) (hk : k > 1) (x : ℝ) (hx : 0 ≤ x ∧ x ≤ 1) :
    alpha k * Real.binEntropy (x ^ k) ≥ x ^ (k - 1) * Real.binEntropy x := by
  -- Since $q(x)$ is continuous on $(0, 1)$ and tends to $1/k$ at endpoints (Lemma 1), we can extend $q$ to $[0, 1]$ by setting $q(0)=q(1)=1/k$.
  set q_ext : ℝ → ℝ := fun x => if x = 0 ∨ x = 1 then 1 / k else q k x
  have hq_ext_continuous : ContinuousOn q_ext (Set.Icc 0 1) := by
    -- By definition of $q_ext$, we know that it is continuous on $(0, 1)$ and tends to $1/k$ at endpoints.
    have hq_ext_cont : ContinuousOn (fun x => if x = 0 ∨ x = 1 then 1 / k else q k x) (Set.Icc 0 1) := by
      have h_cont_at_0 : Filter.Tendsto (q k) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / k)) := by
        exact lemma_l1_zero k hk
      have h_cont_at_1 : Filter.Tendsto (q k) (nhdsWithin 1 (Set.Iio 1)) (nhds (1 / k)) := by
        convert lemma_l1_one k hk using 1
      intro x hx; by_cases hx0 : x = 0 <;> by_cases hx1 : x = 1 <;> simp_all +decide [ ContinuousWithinAt ] ;
      · rw [ Metric.tendsto_nhdsWithin_nhds ] at *;
        intro ε hε; rcases h_cont_at_0 ε hε with ⟨ δ, hδ, H ⟩ ; use δ, hδ; intro x hx₁ hx₂; cases eq_or_lt_of_le hx₁.out <;> aesop;
      · rw [ Metric.tendsto_nhdsWithin_nhds ] at *;
        intro ε hε; rcases h_cont_at_1 ε hε with ⟨ δ, hδ, H ⟩ ; use δ, hδ; intro x hx₁ hx₂; cases eq_or_lt_of_le hx₁.out <;> aesop;
      · refine' Filter.Tendsto.congr' _ _;
        use fun x => q k x;
        · filter_upwards [ eventually_nhdsWithin_of_eventually_nhds ( isOpen_compl_singleton.mem_nhds hx0 ), eventually_nhdsWithin_of_eventually_nhds ( isOpen_compl_singleton.mem_nhds hx1 ) ] with y hy0 hy1 using by aesop;
        · refine' Filter.Tendsto.mono_left _ nhdsWithin_le_nhds;
          refine' ContinuousAt.div _ _ _ <;> norm_num [ Real.binEntropy ];
          · exact ContinuousAt.mul ( ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl hx0 ) <| ContinuousAt.add ( ContinuousAt.neg <| ContinuousAt.mul continuousAt_id <| Real.continuousAt_log hx0 ) <| ContinuousAt.neg <| ContinuousAt.mul ( continuousAt_const.sub continuousAt_id ) <| ContinuousAt.log ( continuousAt_const.sub continuousAt_id ) <| by contrapose! hx1; linarith;
          · refine' ContinuousAt.add _ _;
            · exact ContinuousAt.neg ( ContinuousAt.mul ( ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl hx0 ) <| ContinuousAt.log ( ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl hx0 ) <| ne_of_gt <| Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 <| Ne.symm hx0 ) _ );
            · exact ContinuousAt.neg ( ContinuousAt.mul ( continuousAt_const.sub ( continuousAt_id.rpow_const <| Or.inr <| by linarith ) ) <| ContinuousAt.log ( continuousAt_const.sub ( continuousAt_id.rpow_const <| Or.inr <| by linarith ) ) <| by exact ne_of_gt <| sub_pos.mpr <| Real.rpow_lt_one ( by linarith ) ( lt_of_le_of_ne hx.2 hx1 ) <| by linarith );
          · cases lt_or_gt_of_ne hx0 <;> cases lt_or_gt_of_ne hx1 <;> nlinarith [ Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) k, Real.rpow_lt_one hx.1 ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith : 0 < k ), Real.log_le_sub_one_of_pos ( Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) k ), Real.log_le_sub_one_of_pos ( sub_pos.mpr ( Real.rpow_lt_one hx.1 ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith : 0 < k ) ) ) ];
    convert hq_ext_cont using 1;
  -- Since $q_ext$ is continuous on $[0, 1]$ and tends to $1/k$ at endpoints (Lemma 1), it must attain a maximum value $M$ on $[0, 1]$.
  obtain ⟨M, hM⟩ : ∃ M, (∀ x ∈ Set.Icc 0 1, q_ext x ≤ M) ∧ (∃ x ∈ Set.Icc 0 1, q_ext x = M) := by
    exact ⟨ SupSet.sSup ( q_ext '' Set.Icc 0 1 ), fun x hx => le_csSup ( IsCompact.bddAbove ( isCompact_Icc.image_of_continuousOn hq_ext_continuous ) ) ( Set.mem_image_of_mem _ hx ), by simpa using ( IsCompact.sSup_mem ( isCompact_Icc.image_of_continuousOn hq_ext_continuous ) <| Set.Nonempty.image _ <| Set.nonempty_Icc.mpr zero_le_one ) ⟩;
  -- If $M$ is attained at the boundary, then $M = 1/k < \alpha_k$, so $q_ext(x) \le \alpha_k$ for all $x \in [0, 1]$.
  by_cases hM_boundary : M = 1 / k;
  · -- If $M$ is attained at the boundary, then $M = 1/k < \alpha_k$, so $q_ext(x) \le \alpha_k$ for all $x \in [0, 1]$. Hence, $q(x) \le \alpha_k$ for all $x \in (0, 1)$.
    have hq_le_alpha : ∀ x ∈ Set.Ioo 0 1, q k x ≤ alpha k := by
      intros x hx
      have hq_le_M : q k x ≤ M := by
        grind;
      exact hq_le_M.trans ( hM_boundary.symm ▸ by simpa using lemma_l2 k hk |> le_of_lt );
    by_cases hx0 : x = 0 <;> by_cases hx1 : x = 1 <;> simp_all +decide [ Real.binEntropy ];
    · norm_num [ show k ≠ 0 by positivity ];
    · convert mul_le_mul_of_nonneg_right ( hq_le_alpha x ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) ( lt_of_le_of_ne hx.2 hx1 ) ) ( show 0 ≤ - ( x ^ k * Real.log ( x ^ k ) ) + - ( ( 1 - x ^ k ) * Real.log ( 1 - x ^ k ) ) from ?_ ) using 1;
      · unfold q; rw [ Real.log_rpow ( by linarith [ show x > 0 from lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ] ) ] ; ring_nf;
        field_simp;
        rw [ eq_div_iff ];
        · unfold Real.binEntropy; ring_nf;
          rw [ Real.log_inv, Real.log_inv, Real.log_rpow ( by linarith [ show x > 0 from lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ] ) ] ; ring_nf;
          rw [ Real.log_inv, Real.log_inv ] ; ring;
        · unfold Real.binEntropy;
          norm_num;
          nlinarith [ show x ^ k > 0 by exact Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) _, show x ^ k < 1 by exact Real.rpow_lt_one ( by linarith ) ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith ), Real.log_le_sub_one_of_pos ( show 0 < x ^ k by exact Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) _ ), Real.log_le_sub_one_of_pos ( show 0 < 1 - x ^ k by exact sub_pos.mpr ( Real.rpow_lt_one ( by linarith ) ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith ) ) ) ];
      · nlinarith [ Real.log_le_sub_one_of_pos ( show 0 < x ^ k by exact Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) _ ), Real.log_le_sub_one_of_pos ( show 0 < 1 - x ^ k by exact sub_pos.mpr ( Real.rpow_lt_one ( by linarith ) ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith ) ) ), Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) k, Real.rpow_lt_one ( by linarith ) ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith : 0 < k ) ];
  · -- If $M$ is attained in $(0, 1)$, then $q'(c) = 0$ for some $c \in (0, 1)$.
    obtain ⟨c, hc⟩ : ∃ c ∈ Set.Ioo 0 1, q_ext c = M ∧ deriv (q k) c = 0 := by
      obtain ⟨c, hc⟩ : ∃ c ∈ Set.Ioo 0 1, q_ext c = M := by
        grind;
      have h_deriv_zero : deriv (q k) c = 0 := by
        have h_max : ∀ x ∈ Set.Ioo 0 1, q k x ≤ q k c := by
          grind
        exact IsLocalMax.deriv_eq_zero ( Filter.eventually_of_mem ( Ioo_mem_nhds hc.1.1 hc.1.2 ) h_max );
      tauto;
    -- By `q_deriv_eq_zero_iff`, $q'(c)=0 \iff BoppanaG(c) = BoppanaG(c^k)$.
    have hBoppanaG_eq : BoppanaG c = BoppanaG (c ^ k) := by
      exact q_deriv_eq_zero_iff k hk c ⟨ hc.1.1, hc.1.2 ⟩ |>.1 hc.2.2;
    -- By `BoppanaG_eq_iff`, this implies $c^k = c$ or $c^k = 1 - c$.
    have hck_eq : c ^ k = c ∨ c ^ k = 1 - c := by
      apply (BoppanaG_eq_iff c (c ^ k) ⟨hc.left.left, hc.left.right⟩ ⟨Real.rpow_pos_of_pos hc.left.left k, Real.rpow_lt_one hc.left.left.le hc.left.right (by linarith)⟩).mp hBoppanaG_eq |> Or.imp (fun h => by
        linarith) (fun h => by
        linarith);
    -- Since $c \in (0, 1)$ and $k > 1$, $c^k < c$, so $c^k \ne c$.
    have hck_ne_c : c ^ k ≠ c := by
      exact ne_of_lt ( by simpa using Real.rpow_lt_rpow_of_exponent_gt hc.1.1 hc.1.2 hk );
    -- Since $c^k = 1 - c$, by `lemma_l5`, this implies $c = 1/(1+\alpha_k)$.
    have hc_eq : c = 1 / (1 + alpha k) := by
      apply lemma_l5 k hk c ⟨hc.left.left, hc.left.right⟩ (hck_eq.resolve_left hck_ne_c);
    -- By `lemma_q_alpha`, $q(c) = \alpha_k$.
    have hq_c : q_ext c = alpha k := by
      convert lemma_q_alpha k hk using 1;
      simp +zetaDelta at *;
      rw [ hc_eq, if_neg ( by rintro ( h | h ) <;> linarith ) ];
    -- Since $M$ is the maximum value of $q_ext$ on $[0, 1]$, we have $q_ext(x) \le M$ for all $x \in [0, 1]$.
    have hq_ext_le_M : ∀ x ∈ Set.Icc 0 1, q_ext x ≤ M := by
      exact hM.1;
    by_cases hx0 : x = 0 <;> by_cases hx1 : x = 1 <;> simp_all +decide;
    · norm_num [ show k ≠ 0 by linarith ];
    · convert mul_le_mul_of_nonneg_right ( hq_ext_le_M x hx.1 hx.2 ) ( show 0 ≤ Real.binEntropy ( x ^ k ) from _ ) using 1;
      · simp +zetaDelta at *;
        rw [ if_neg ( by aesop ) ] ; unfold q ; ring_nf;
        rw [ mul_assoc, mul_inv_cancel₀ ( ne_of_gt ( show 0 < Real.binEntropy ( x ^ k ) from _ ) ), mul_one ];
        unfold Real.binEntropy;
        rw [ Real.log_inv, Real.log_inv ];
        exact add_pos_of_nonneg_of_pos ( mul_nonneg ( Real.rpow_nonneg hx.1 _ ) ( neg_nonneg_of_nonpos ( Real.log_nonpos ( Real.rpow_nonneg hx.1 _ ) ( Real.rpow_le_one hx.1 hx.2 ( by positivity ) ) ) ) ) ( mul_pos ( sub_pos.mpr ( Real.rpow_lt_one hx.1 ( lt_of_le_of_ne hx.2 hx1 ) ( by positivity ) ) ) ( neg_pos.mpr ( Real.log_neg ( sub_pos.mpr ( Real.rpow_lt_one hx.1 ( lt_of_le_of_ne hx.2 hx1 ) ( by positivity ) ) ) ( sub_lt_self _ ( Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) _ ) ) ) ) );
      · unfold Real.binEntropy;
        rw [ Real.log_inv, Real.log_inv ];
        nlinarith [ Real.log_le_sub_one_of_pos ( show 0 < x ^ k by exact Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) _ ), Real.log_le_sub_one_of_pos ( show 0 < 1 - x ^ k by exact sub_pos.mpr ( Real.rpow_lt_one ( by linarith ) ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith ) ) ), Real.rpow_nonneg hx.1 k, Real.rpow_le_one hx.1 hx.2 ( by linarith : 0 ≤ k ) ]

/-
The extended function $q$ is continuous on $[0, 1]$.
-/
noncomputable def q_extended (k : ℝ) (x : ℝ) : ℝ :=
  if x ≤ 0 ∨ x ≥ 1 then 1 / k else q k x

lemma q_extended_continuous (k : ℝ) (hk : k > 1) :
    ContinuousOn (q_extended k) (Set.Icc 0 1) := by
  unfold q_extended;
  -- We'll use the fact that $q(k, x)$ is continuous on $[0, 1]$ and that $q(k, 0) = q(k, 1) = 1/k$.
  have h_cont : ContinuousOn (fun x => q k x) (Set.Ioo 0 1) ∧ Filter.Tendsto (q k) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / k)) ∧ Filter.Tendsto (q k) (nhdsWithin 1 (Set.Iio 1)) (nhds (1 / k)) := by
    refine' ⟨ _, lemma_l1_zero k hk, lemma_l1_one k hk ⟩;
    refine' ContinuousOn.div _ _ _;
    · refine' ContinuousOn.mul _ _;
      · exact continuousOn_of_forall_continuousAt fun x hx => ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl <| ne_of_gt hx.1;
      · refine' ContinuousOn.add _ _;
        · exact ContinuousOn.mul continuousOn_id ( ContinuousOn.log ( continuousOn_id.inv₀ fun x hx => ne_of_gt hx.1 ) fun x hx => ne_of_gt ( inv_pos.mpr hx.1 ) );
        · exact ContinuousOn.mul ( continuousOn_const.sub continuousOn_id ) ( ContinuousOn.log ( ContinuousOn.inv₀ ( continuousOn_const.sub continuousOn_id ) fun x hx => by linarith [ hx.1, hx.2 ] ) fun x hx => by exact ne_of_gt ( inv_pos.mpr ( by linarith [ hx.1, hx.2 ] ) ) );
    · refine' ContinuousOn.add _ _;
      · exact ContinuousOn.mul ( ContinuousOn.rpow continuousOn_id continuousOn_const <| by intro x hx; exact Or.inl <| ne_of_gt hx.1 ) <| ContinuousOn.log ( ContinuousOn.inv₀ ( continuousOn_id.rpow continuousOn_const <| by intro x hx; exact Or.inl <| ne_of_gt hx.1 ) <| by intro x hx; exact ne_of_gt <| Real.rpow_pos_of_pos hx.1 _ ) <| by intro x hx; exact ne_of_gt <| inv_pos.mpr <| Real.rpow_pos_of_pos hx.1 _;
      · exact ContinuousOn.mul ( continuousOn_const.sub ( continuousOn_of_forall_continuousAt fun x hx => by exact ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl <| by linarith [ hx.1 ] ) ) ( ContinuousOn.log ( ContinuousOn.inv₀ ( continuousOn_const.sub ( continuousOn_of_forall_continuousAt fun x hx => by exact ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl <| by linarith [ hx.1 ] ) ) fun x hx => by exact ne_of_gt <| sub_pos.mpr <| Real.rpow_lt_one hx.1.le hx.2 <| by linarith ) fun x hx => by exact ne_of_gt <| inv_pos.mpr <| sub_pos.mpr <| Real.rpow_lt_one hx.1.le hx.2 <| by linarith );
    · exact fun x hx => ne_of_gt <| Real.binEntropy_pos ( Real.rpow_pos_of_pos hx.1 _ ) ( Real.rpow_lt_one hx.1.le hx.2 ( by positivity ) );
  intro x hx; by_cases hx0 : x = 0 <;> by_cases hx1 : x = 1 <;> simp_all +decide [ ContinuousWithinAt ] ;
  · rw [ Metric.tendsto_nhdsWithin_nhds ] at *;
    intro ε hε; rcases h_cont.2.1 ε hε with ⟨ δ, hδ, H ⟩ ; use δ, hδ; intro x hx hx'; cases eq_or_lt_of_le hx.out <;> aesop;
  · rw [ Metric.tendsto_nhdsWithin_nhds ] at *;
    intro ε hε; rcases h_cont.2.2.eventually ( Metric.ball_mem_nhds _ hε ) with h; rcases Metric.mem_nhdsWithin_iff.mp h with ⟨ δ, hδ, hδ' ⟩ ; use Min.min δ 1; aesop;
  · rw [ if_neg ( by rintro ( h | h ) <;> cases lt_or_gt_of_ne hx0 <;> cases lt_or_gt_of_ne hx1 <;> linarith ) ];
    refine' Filter.Tendsto.congr' _ ( h_cont.1.continuousAt ( Ioo_mem_nhds ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) ( lt_of_le_of_ne hx.2 hx1 ) ) |> Filter.Tendsto.mono_left <| nhdsWithin_le_nhds );
    filter_upwards [ eventually_nhdsWithin_of_eventually_nhds ( Ioo_mem_nhds ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) ( lt_of_le_of_ne hx.2 hx1 ) ) ] with y hy using by rw [ if_neg ( by rintro ( hy' | hy' ) <;> linarith [ hy.1, hy.2 ] ) ] ;

/-
The function q is differentiable on (0, 1).
-/
lemma q_differentiable (k : ℝ) (hk : k > 1) :
    DifferentiableOn ℝ (q k) (Set.Ioo 0 1) := by
      refine' DifferentiableOn.div _ _ _;
      · refine' DifferentiableOn.mul _ _;
        · exact DifferentiableOn.rpow differentiableOn_id ( differentiableOn_const _ ) ( by aesop );
        · refine' DifferentiableOn.add _ _;
          · exact DifferentiableOn.mul differentiableOn_id ( DifferentiableOn.log ( differentiableOn_id.inv fun x hx => ne_of_gt hx.1 ) fun x hx => ne_of_gt ( inv_pos.mpr hx.1 ) );
          · exact DifferentiableOn.mul ( differentiableOn_id.const_sub _ ) ( DifferentiableOn.log ( DifferentiableOn.inv ( differentiableOn_id.const_sub _ ) fun x hx => by linarith [ hx.1, hx.2 ] ) fun x hx => by exact ne_of_gt ( inv_pos.mpr ( by linarith [ hx.1, hx.2 ] ) ) );
      · refine' DifferentiableOn.add _ _ <;> norm_num [ Real.differentiableAt_binEntropy ];
        · exact DifferentiableOn.mul ( DifferentiableOn.rpow ( differentiableOn_id ) ( differentiableOn_const _ ) ( by aesop ) ) ( DifferentiableOn.log ( DifferentiableOn.rpow ( differentiableOn_id ) ( differentiableOn_const _ ) ( by aesop ) ) ( by intro x hx; exact ne_of_gt ( Real.rpow_pos_of_pos hx.1 _ ) ) );
        · exact DifferentiableOn.mul ( DifferentiableOn.sub ( differentiableOn_const _ ) ( DifferentiableOn.rpow ( differentiableOn_id ) ( differentiableOn_const _ ) ( by intro x hx; linarith [ hx.1, hx.2 ] ) ) ) ( DifferentiableOn.log ( DifferentiableOn.sub ( differentiableOn_const _ ) ( DifferentiableOn.rpow ( differentiableOn_id ) ( differentiableOn_const _ ) ( by intro x hx; linarith [ hx.1, hx.2 ] ) ) ) ( by intro x hx; exact ne_of_gt ( sub_pos.mpr ( Real.rpow_lt_one hx.1.le hx.2 ( by linarith ) ) ) ) );
      · norm_num [ Real.binEntropy ];
        intro x hx₁ hx₂; nlinarith [ show x ^ k > 0 by positivity, show x ^ k < 1 by exact Real.rpow_lt_one hx₁.le hx₂ ( by positivity ), Real.log_le_sub_one_of_pos ( show 0 < x ^ k by positivity ), Real.log_le_sub_one_of_pos ( show 0 < 1 - x ^ k by exact sub_pos.mpr ( Real.rpow_lt_one hx₁.le hx₂ ( by positivity ) ) ) ] ;

/-
The derivative of q is zero at x iff x = 1/(1+alpha).
-/
lemma q_critical_point (k : ℝ) (hk : k > 1) (x : ℝ) (hx : 0 < x ∧ x < 1) :
    deriv (q k) x = 0 ↔ x = 1 / (1 + alpha k) := by
      constructor;
      · intro h_deriv_zero
        have h_eq : x = x ^ k ∨ x = 1 - x ^ k := by
          have h_eq : BoppanaG x = BoppanaG (x ^ k) := by
            exact (q_deriv_eq_zero_iff k hk x hx).mp h_deriv_zero;
          apply (BoppanaG_eq_iff x ( x ^ k ) hx ⟨ Real.rpow_pos_of_pos hx.1 _, Real.rpow_lt_one hx.1.le hx.2 ( by linarith ) ⟩ ) |>.1 h_eq;
        -- Since $x \in (0, 1)$ and $k > 1$, $x = x^k$ is impossible (implies $x^{k-1} = 1$).
        have h_impossible : x ≠ x ^ k := by
          exact ne_of_gt ( by simpa using Real.rpow_lt_rpow_of_exponent_gt hx.1 hx.2 hk );
        exact lemma_l5 k hk x hx ( by linarith [ h_eq.resolve_left h_impossible ] ) ▸ by norm_num;
      · intro hx_eq;
        -- By definition of $q$, we know that $q(x) = \alpha_k$.
        have h_q_eq_alpha : q k x = alpha k := by
          rw [ hx_eq, lemma_q_alpha ];
          exact RCLike.ofReal_lt_ofReal.mp hk;
        -- By definition of $q$, we know that $q(x)$ is maximized at $x = 1 / (1 + \alpha_k)$.
        have h_max : ∀ y ∈ Set.Ioo 0 1, q k y ≤ alpha k := by
          -- By definition of $q$, we know that $q(x) = \frac{x^{k-1} h(x)}{h(x^k)}$.
          intro y hy
          simp [q];
          rw [ div_le_iff₀ ];
          · convert generalized_boppana k hk y ⟨ hy.1.le, hy.2.le ⟩ |> le_trans <| le_of_eq _ using 1;
            norm_cast;
          · unfold Real.binEntropy;
            norm_num [ Real.log_inv ];
            nlinarith [ Real.log_le_sub_one_of_pos ( show 0 < 1 - y ^ k by exact sub_pos.mpr ( Real.rpow_lt_one hy.1.le hy.2 ( by linarith ) ) ), Real.log_le_sub_one_of_pos ( show 0 < y ^ k by exact Real.rpow_pos_of_pos hy.1 _ ), Real.rpow_pos_of_pos hy.1 k, Real.rpow_lt_one hy.1.le hy.2 ( by linarith : 0 < k ) ];
        exact IsLocalMax.deriv_eq_zero ( Filter.eventually_of_mem ( Ioo_mem_nhds hx.1 hx.2 ) fun y hy => by simpa [ h_q_eq_alpha ] using h_max y hy )

/-
q_extended is bounded by alpha k on [0, 1], with equality iff x = 1/(1+alpha k).
-/
lemma q_bounded (k : ℝ) (hk : k > 1) :
    ∀ x ∈ Set.Icc 0 1, q_extended k x ≤ alpha k ∧ (q_extended k x = alpha k ↔ x = 1 / (1 + alpha k)) := by
      -- Apply lemma_l3 to f = q_extended k with M = alpha k and a = 1 / (1 + alpha k).
      have h_l3 : ∀ x ∈ Set.Icc 0 1, q_extended k x ≤ alpha k ∧ (q_extended k x = alpha k ↔ x = 1 / (1 + alpha k)) := by
        have h_cont : ContinuousOn (q_extended k) (Set.Icc 0 1) := by
          convert q_extended_continuous k hk using 1
        have h_diff : DifferentiableOn ℝ (q_extended k) (Set.Ioo 0 1) := by
          exact DifferentiableOn.congr ( q_differentiable k hk ) fun x hx => if_neg <| by aesop;
        have h_bounds : q_extended k 0 < alpha k ∧ q_extended k 1 < alpha k := by
          unfold q_extended;
          norm_num [ lemma_l2 k hk ];
          exact lt_of_le_of_lt ( by norm_num ) ( lemma_l2 k hk )
        have hα : 0 < alpha k := alpha_pos k hk
        have h_critical : q_extended k (1 / (1 + alpha k)) = alpha k := by
          rw [ show q_extended k ( 1 / ( 1 + alpha k ) ) = q k ( 1 / ( 1 + alpha k ) ) from ?_ ];
          · convert lemma_q_alpha k hk;
          · exact if_neg (by rintro (h | h) <;> nlinarith [hα, one_div_mul_cancel (by linarith : (1 + alpha k) ≠ 0)])
        have h_deriv : ∀ x ∈ Set.Ioo 0 1, deriv (q_extended k) x = 0 ↔ x = 1 / (1 + alpha k) := by
          intro x hx; rw [ show deriv ( q_extended k ) x = deriv ( q k ) x from Filter.EventuallyEq.deriv_eq <| Filter.eventuallyEq_of_mem ( Ioo_mem_nhds hx.1 hx.2 ) fun y hy => if_neg <| by aesop ] ; exact q_critical_point k hk x hx;
        apply lemma_l3;
        any_goals tauto;
        norm_num +zetaDelta at *;
        exact ⟨by linarith [hα], inv_lt_one_of_one_lt₀ <| by linarith [hα]⟩;
      assumption

/-
The generalized Boppana inequality holds, with equality iff x is 0, 1, or 1/(1+alpha).
-/
theorem generalized_boppana_full (k : ℝ) (hk : k > 1) (x : ℝ) (hx : 0 ≤ x ∧ x ≤ 1) :
    alpha k * Real.binEntropy (x ^ k) ≥ x ^ (k - 1) * Real.binEntropy x ∧
    (alpha k * Real.binEntropy (x ^ k) = x ^ (k - 1) * Real.binEntropy x ↔
      x = 0 ∨ x = 1 ∨ x = 1 / (1 + alpha k)) := by
        by_cases hx0 : x = 0 <;> by_cases hx1 : x = 1 <;> simp_all +decide;
        · norm_num [ Real.binEntropy, show k ≠ 0 by linarith ];
        · -- Since $x \in (0, 1)$ and $k > 1$, we have $h(x^k) > 0$.
          have h_pos : 0 < Real.binEntropy (x ^ k) := by
            unfold Real.binEntropy;
            have h_pos : 0 < x ^ k ∧ x ^ k < 1 := by
              exact ⟨ Real.rpow_pos_of_pos ( lt_of_le_of_ne hx.1 ( Ne.symm hx0 ) ) _, Real.rpow_lt_one ( by linarith ) ( lt_of_le_of_ne hx.2 hx1 ) ( by linarith ) ⟩;
            field_simp;
            exact add_pos ( mul_pos h_pos.1 ( Real.log_pos ( one_lt_one_div h_pos.1 h_pos.2 ) ) ) ( mul_pos ( sub_pos.mpr h_pos.2 ) ( Real.log_pos ( one_lt_one_div ( sub_pos.mpr h_pos.2 ) ( sub_lt_self _ h_pos.1 ) ) ) );
          -- The inequality is equivalent to $\alpha \geq \frac{x^{k-1} h(x)}{h(x^k)} = q(x)$.
          suffices h_eq : alpha k ≥ x ^ (k - 1) * Real.binEntropy x / Real.binEntropy (x ^ k) ∧ (alpha k = x ^ (k - 1) * Real.binEntropy x / Real.binEntropy (x ^ k) ↔ x = 1 / (1 + alpha k)) by
            exact ⟨ by rw [ ge_iff_le, div_le_iff₀ h_pos ] at h_eq; linarith, by rw [ eq_div_iff h_pos.ne' ] at h_eq; aesop ⟩;
          convert q_bounded k hk x ⟨ hx.1, hx.2 ⟩ using 1;
          · rw [ show q_extended k x = x ^ ( k - 1 ) * Real.binEntropy x / Real.binEntropy ( x ^ k ) from _ ];
            exact if_neg ( by rintro ( h | h ) <;> cases lt_or_gt_of_ne hx0 <;> cases lt_or_gt_of_ne hx1 <;> linarith );
          · field_simp;
            rw [ show q_extended k x = x ^ ( k - 1 ) * Real.binEntropy x / Real.binEntropy ( x ^ k ) from ?_ ];
            · rw [ div_eq_iff h_pos.ne' ] ; ring_nf;
              rw [ eq_comm ];
            · exact if_neg ( by rintro ( h | h ) <;> cases lt_or_gt_of_ne hx0 <;> cases lt_or_gt_of_ne hx1 <;> linarith )
