"""Pauli-string algebra, symplectic closures and dynamical Lie algebras -- exact, integer.

Encoding
--------
A Pauli string on ``n`` qubits is ``Q_v = X^{a} Z^{b}`` with ``v = (a|b) in F_2^{2n}``, packed
into one python/numpy integer: bits ``0..n-1`` hold ``a``, bits ``n..2n-1`` hold ``b``.

Two exact facts drive everything here.

1.  ``Q_v Q_w = (-1)^{b_v . a_w} Q_{v+w}``  (integer dot product mod 2, ``+`` is XOR).
2.  ``[Q_v, Q_w] = ( (-1)^{b_v . a_w} - (-1)^{b_w . a_v} ) Q_{v+w}``,
    which is ``0`` when the two strings commute and ``+-2 Q_{v+w}`` when they anticommute.

Consequence: the real span of the Pauli strings is a Lie algebra with INTEGER structure
constants in ``{0, +-2}``, and the Lie algebra generated by a set of *single* Pauli strings is
spanned by Pauli strings.  Computing it is therefore a purely combinatorial closure in
``F_2^{2n}`` under ``v, w -> v + w`` whenever the symplectic form ``<v,w> = 1``.

``<v,w> = b_v . a_w + b_w . a_v  (mod 2)``.
"""

from __future__ import annotations

import numpy as np

__all__ = [
    "pauli_x",
    "pauli_z",
    "zz",
    "symplectic_form",
    "anticommute",
    "dla_pauli_closure",
    "tfim_generators",
    "frustration_graph",
    "has_induced_claw",
    "find_induced_claw",
    "is_line_graph_certificate",
    "lie_closure_dim",
]


def pauli_x(n: int, i: int) -> int:
    return 1 << i


def pauli_z(n: int, i: int) -> int:
    return 1 << (n + i)


def zz(n: int, i: int, j: int) -> int:
    return (1 << (n + i)) | (1 << (n + j))


def symplectic_form(v: int, w: int, n: int) -> int:
    mask = (1 << n) - 1
    av, bv = v & mask, (v >> n) & mask
    aw, bw = w & mask, (w >> n) & mask
    return (bin(bv & aw).count("1") + bin(bw & av).count("1")) & 1


def anticommute(v: int, w: int, n: int) -> bool:
    return symplectic_form(v, w, n) == 1


# ---------------------------------------------------------------------------
# generators
# ---------------------------------------------------------------------------


def tfim_generators(sites, bonds, n=None):
    """Transverse-field Ising generators: ``X_i`` for each site, ``Z_i Z_j`` for each bond.

    Returns ``(gens, labels, n)``.  This is EXACTLY the generator set of the layer transfer
    operator of the ``(d+1)``-dimensional classical Ising model on a ``d``-dimensional layer:

        V = exp(K* sum_i X_i) exp(sum_{<ij>} K Z_i Z_j)   (up to a scalar).
    """
    if n is None:
        n = len(sites)
    gens, labels = [], []
    for i in sites:
        gens.append(pauli_x(n, i))
        labels.append(("X", i))
    for i, j in bonds:
        gens.append(zz(n, i, j))
        labels.append(("ZZ", i, j))
    return gens, labels, n


# ---------------------------------------------------------------------------
# symplectic (dynamical Lie algebra) closure
# ---------------------------------------------------------------------------


def dla_pauli_closure(gens, n: int, max_size: int = 1 << 22, report=None):
    """Closure of ``gens`` under ``v,w -> v+w`` whenever ``<v,w> = 1``.

    Returns ``(elements_sorted, saturated)``.  ``elements`` is exactly the set of Pauli strings
    spanning the dynamical Lie algebra generated by ``{i Q_g}``; its cardinality is the DLA
    dimension.
    """
    mask = (1 << n) - 1
    seen = set(int(g) for g in gens)
    arr = np.array(sorted(seen), dtype=np.int64)
    queue = list(arr)
    head = 0
    while head < len(queue):
        v = int(queue[head])
        head += 1
        av = np.int64(v & mask)
        bv = np.int64((v >> n) & mask)
        aW = arr & mask
        bW = (arr >> n) & mask
        sp = (np.bitwise_count(bv & aW) + np.bitwise_count(bW & av)) & 1
        idx = np.nonzero(sp)[0]
        if idx.size == 0:
            continue
        sums = np.bitwise_xor(np.int64(v), arr[idx])
        fresh = []
        for s in sums.tolist():
            if s not in seen:
                seen.add(s)
                fresh.append(s)
        if fresh:
            if len(seen) > max_size:
                return sorted(seen), False
            arr = np.concatenate([arr, np.array(sorted(fresh), dtype=np.int64)])
            queue.extend(fresh)
            if report and len(seen) % report < len(fresh):
                print(f"    ... {len(seen)} elements", flush=True)
    return sorted(seen), True


# ---------------------------------------------------------------------------
# frustration graph and the claw obstruction
# ---------------------------------------------------------------------------


def frustration_graph(gens, n: int):
    """Adjacency sets: vertex ``a`` ~ vertex ``b`` iff the Pauli terms ANTICOMMUTE."""
    m = len(gens)
    adj = [set() for _ in range(m)]
    for a in range(m):
        for b in range(a + 1, m):
            if symplectic_form(int(gens[a]), int(gens[b]), n):
                adj[a].add(b)
                adj[b].add(a)
    return adj


def find_induced_claw(adj):
    """Return an induced ``K_{1,3}`` as ``(centre, [l1,l2,l3])`` or ``None``.

    A claw is a vertex with three pairwise NON-adjacent neighbours.
    """
    for c, nb in enumerate(adj):
        nbl = sorted(nb)
        for i in range(len(nbl)):
            for j in range(i + 1, len(nbl)):
                if nbl[j] in adj[nbl[i]]:
                    continue
                for k in range(j + 1, len(nbl)):
                    if nbl[k] in adj[nbl[i]] or nbl[k] in adj[nbl[j]]:
                        continue
                    return c, [nbl[i], nbl[j], nbl[k]]
    return None


def has_induced_claw(adj) -> bool:
    return find_induced_claw(adj) is not None


def is_line_graph_certificate(adj):
    """Beineke: a line graph has no induced ``K_{1,3}``.  Returns (is_claw_free, witness)."""
    w = find_induced_claw(adj)
    return (w is None), w


# ---------------------------------------------------------------------------
# Lie closure of general (non-monomial) elements, over F_p
# ---------------------------------------------------------------------------


def _commutator(e1: dict, e2: dict, n: int, p: int) -> dict:
    """``[sum c_v Q_v, sum d_w Q_w]`` with coefficients mod p.  Structure constants in {0,+-2}."""
    mask = (1 << n) - 1
    out: dict[int, int] = {}
    for v, c in e1.items():
        av, bv = v & mask, (v >> n) & mask
        for w, d in e2.items():
            aw, bw = w & mask, (w >> n) & mask
            s1 = bin(bv & aw).count("1") & 1
            s2 = bin(bw & av).count("1") & 1
            if s1 == s2:
                continue
            sign = 2 if s1 == 0 else -2
            k = v ^ w
            out[k] = (out.get(k, 0) + sign * c * d) % p
    return {k: v for k, v in out.items() if v % p}


def _reduce(vec: dict, basis: dict, p: int):
    """Row-reduce ``vec`` against echelon ``basis`` (leading key -> normalised row)."""
    vec = dict(vec)
    while vec:
        lead = max(vec)
        if lead not in basis:
            inv = pow(vec[lead], p - 2, p)
            return lead, {k: (c * inv) % p for k, c in vec.items()}
        row = basis[lead]
        f = vec[lead]
        for k, c in row.items():
            nv = (vec.get(k, 0) - f * c) % p
            if nv:
                vec[k] = nv
            else:
                vec.pop(k, None)
    return None, None


def lie_closure_dim(generators, n: int, p: int = (1 << 61) - 1, max_dim: int = 200000,
                    return_basis: bool = False):
    """Dimension of the Lie algebra generated by ``generators`` (list of dicts ``{v: coeff}``).

    Computed over ``F_p``; the true dimension over ``Q`` is ``>=`` this, and equality holds unless
    ``p`` divides a minor.  Run with two different primes to be safe.
    """
    basis: dict[int, dict] = {}
    order: list[dict] = []
    pending = [dict(g) for g in generators]
    while pending:
        g = pending.pop()
        lead, row = _reduce(g, basis, p)
        if lead is None:
            continue
        basis[lead] = row
        order.append(row)
        if len(basis) > max_dim:
            raise MemoryError(f"Lie closure exceeded max_dim={max_dim}")
        for h in list(order):
            c = _commutator(row, h, n, p)
            if c:
                l2, r2 = _reduce(c, basis, p)
                if l2 is not None:
                    pending.append(c)
    if return_basis:
        return len(basis), basis
    return len(basis)
