"""Fast exact Lie-closure for algebras generated by SUMS of Pauli strings.

Why this is fast
----------------
1.  Specht-Wever / Dynkin: the Lie algebra generated by a set ``G`` is spanned by *left-normed*
    brackets ``[g_{i1},[g_{i2},[...,g_{ik}]]]``.  Therefore the generated algebra is the smallest
    subspace containing ``G`` and closed under ``ad_g`` for ``g in G`` only -- ``O(|G| * dim)``
    commutators instead of ``O(dim^2)``.

2.  Each ``ad_g`` for a single Pauli string ``g`` acts on the Pauli-string basis as a signed
    permutation: ``[Q_g, Q_v] = s(g,v) Q_{v XOR g}`` with ``s in {0, +-2}``.  So ``ad_g`` is one
    vectorised gather with a sign, ``O(#columns)``.

3.  The column space (the set of Pauli strings that can ever appear) is found first by a cheap
    BFS with ``|G|`` neighbours per node, not by an ``O(|S|^2)`` pairwise closure.

Arithmetic is exact modulo a prime ``p < 2^31`` so that products fit in ``int64``.
Running with two primes certifies the rank with overwhelming probability; the reported dimension
is always a valid LOWER bound for the rank over ``Q``, and equals it unless ``p`` divides a minor.
"""

from __future__ import annotations

import numpy as np

__all__ = ["support_closure", "generated_lie_dim", "GeneratedAlgebra"]

P1 = 2147483647          # 2^31 - 1, Mersenne prime
P2 = 2147483629          # another 31-bit prime


def _sym(v: int, w: int, n: int) -> int:
    mask = (1 << n) - 1
    return (bin(((v >> n) & mask) & (w & mask)).count("1")
            + bin(((w >> n) & mask) & (v & mask)).count("1")) & 1


def support_closure(seed, single_gens, n, cap=1 << 24):
    """All Pauli strings reachable from ``seed`` by repeatedly bracketing with ``single_gens``."""
    seen = set(int(s) for s in seed)
    queue = list(seen)
    head = 0
    while head < len(queue):
        v = queue[head]
        head += 1
        for g in single_gens:
            if _sym(v, g, n):
                w = v ^ g
                if w not in seen:
                    seen.add(w)
                    queue.append(w)
                    if len(seen) > cap:
                        raise MemoryError(f"support exceeded {cap}")
    return sorted(seen)


class GeneratedAlgebra:
    """Lie algebra generated by a list of elements, each a dict ``{pauli_vector: int coeff}``."""

    def __init__(self, elements, single_gens, n, p=P1):
        self.n = n
        self.p = p
        seed = set()
        for e in elements:
            seed |= set(e)
        self.cols = support_closure(seed, single_gens, n)
        self.index = {v: i for i, v in enumerate(self.cols)}
        self.m = len(self.cols)
        colarr = np.array(self.cols, dtype=np.int64)
        # signed-permutation tables for each single generator
        self.perm = []
        self.sign = []
        for g in single_gens:
            mask = (1 << n) - 1
            a_c = colarr & mask
            b_c = (colarr >> n) & mask
            ag = np.int64(g & mask)
            bg = np.int64((g >> n) & mask)
            s1 = np.bitwise_count(bg & a_c) & 1           # (-1)^{b_g . a_v}
            s2 = np.bitwise_count(b_c & ag) & 1           # (-1)^{b_v . a_g}
            anti = (s1 ^ s2).astype(bool)
            tgt = np.bitwise_xor(colarr, np.int64(g))
            idx = np.full(self.m, -1, dtype=np.int64)
            look = np.array([self.index.get(int(t), -1) for t in tgt], dtype=np.int64)
            idx[anti] = look[anti]
            assert not np.any(idx[anti] < 0), "support closure was incomplete"
            # [Q_g, Q_v] = ((-1)^{b_g.a_v} - (-1)^{b_v.a_g}) Q_{g+v}
            sg = np.zeros(self.m, dtype=np.int64)
            sg[anti] = np.where(s1[anti] == 0, 2, -2)
            self.perm.append(idx)
            self.sign.append(sg)

    def dense(self, e: dict) -> np.ndarray:
        v = np.zeros(self.m, dtype=np.int64)
        for k, c in e.items():
            v[self.index[k]] = c % self.p
        return v

    def ad_single(self, gi: int, vec: np.ndarray) -> np.ndarray:
        out = np.zeros(self.m, dtype=np.int64)
        idx, sg = self.perm[gi], self.sign[gi]
        sel = sg != 0
        # v -> v XOR g is injective, so plain assignment is safe (no index collisions)
        out[idx[sel]] = (sg[sel] * vec[sel]) % self.p
        return out

    def ad_group(self, group: list[int], vec: np.ndarray) -> np.ndarray:
        out = np.zeros(self.m, dtype=np.int64)
        for gi in group:
            out = (out + self.ad_single(gi, vec)) % self.p
        return out

    def closure_dim(self, seeds, ad_groups, max_dim=None, report=None):
        """Close ``seeds`` under the listed ``ad_groups`` (each a list of single-generator indices)."""
        p = self.p
        pivots: dict[int, int] = {}        # column -> row position in ``rows``
        rows: list[np.ndarray] = []

        def reduce_add(vec):
            vec = vec % p
            while True:
                nz = np.nonzero(vec)[0]
                if nz.size == 0:
                    return None
                lead = int(nz[0])
                if lead not in pivots:
                    inv = pow(int(vec[lead]), p - 2, p)
                    vec = (vec * inv) % p
                    pivots[lead] = len(rows)
                    rows.append(vec)
                    return vec
                r = rows[pivots[lead]]
                vec = (vec - int(vec[lead]) * r) % p

        pending = []
        for s in seeds:
            r = reduce_add(self.dense(s) if isinstance(s, dict) else s)
            if r is not None:
                pending.append(r)
        head = 0
        while head < len(pending):
            r = pending[head]
            head += 1
            for grp in ad_groups:
                c = self.ad_group(grp, r)
                if np.any(c):
                    nr = reduce_add(c)
                    if nr is not None:
                        pending.append(nr)
                        if max_dim and len(rows) > max_dim:
                            raise MemoryError(f"exceeded max_dim={max_dim}")
                        if report and len(rows) % report == 0:
                            print(f"      dim {len(rows)} ...", flush=True)
        return len(rows)


def generated_lie_dim(elements, single_gens, n, groups=None, p=P1, max_dim=None, report=None):
    """Dimension of the Lie algebra generated by ``elements`` (dicts of Pauli strings).

    ``single_gens`` must contain every Pauli string occurring in ``elements``; ``groups`` lists,
    for each generating ELEMENT, the indices into ``single_gens`` of its Pauli terms.
    """
    alg = GeneratedAlgebra(elements, single_gens, n, p=p)
    if groups is None:
        groups = []
        for e in elements:
            groups.append([single_gens.index(k) for k in e])
    return alg.closure_dim(elements, groups, max_dim=max_dim, report=report), alg.m
