"""s3_routeF_decompose.py — Route F (exploratory, pre-statement Route C
extension): eigen-jump / z-eigenvalue census as a RANK certificate SOURCE.
Origin: turns the family (L_1, L_i, L_j) into (I_8, L_i, L_j); decomposing
I_8 = sum_s u_s v_s^T with joint diagonalization of the remaining pencil...

For the R-closed specific triple (1, i, j): I_8 has the 8-term standard
decomposition; the question whether some clever u_s, v_s make BOTH L_i
and L_j simultaneously sparse low-rank. The classical H-algebra trick:
on H (n=4), tau has rank 7 = 4 + 3 from the FIDUCCIA-style sparse
diagonalization: I = sum over the 4 coordinate idempotents + the
off-diagonal 3 = rank-3 of the imaginary pair (L_i, L_j) restricted to
the orthogonal complement of span{1}? Exact analog:

 设法 decompose: I_8 = sum_{c=1..8} e_c e_c^T (8 terms standard).
 On the 2-complement? The octonion pencil (L_i, L_j) generates a
 QUATERNION subalgebra H' = span{1, i, j, k}? NO — (i*j)*? not assoc:
 ij = k, but the subalgebra generated by i and j in O is H' = span{1, i,
 j, ij} IS a copy of H (i*j with i,j imaginary units in O: ij is a unit
 orthogonal to 1, i, j, and span{1,i,j,ij} is closed: check exactly
 below). On H' the restriction of the pencil is the Quaternionic tau,
 rank exactly 7; on the orthocomplement (also 4-dim, isomorphic copy
 via the standard octonion doubling), the pencil acts as a second copy.
 So the natural block-diagonal decomposition: rank(T|H') + rank(T|H'perp)
 = 7 + 7 = 14?? That would be an UPPER bound construction if the
 off-diagonal cross-blocks vanish — they DON'T vanish in general (L_i
 maps H' x H'perp nontrivially per the CD doubling structure), so the
 14	UPPER attempt FAILS; the LOWER-side consequence:

   rank(L_u, L_v, L_w) >= rank(block) >= 7 + something?

 EXACT computation here: the restriction maps and cross-block ranks for
 the specific triple, all in fmpq. If the cross terms VANISH for the
 specific (1,i,j), then rank((L_1,L_i,L_j)) = 14 EXACTLY and S3 resolves
 to 14 on that triple — but the chain needs the WORST CASE. If cross
 terms don't vanish, report the block counts as-is (probably 7 + 7 mixed
 with cross-coupling).
"""
import json
import sys
from itertools import combinations
from flint import fmpq, fmpq_mat

sys.path.insert(0, ".")  # noqa: E402
from s3_routeAB import (L_of, mat, rank, conj, E8, cd_mul,  # noqa: E402,F401
                        check_inverse_identity)

Q0, Q1 = fmpq(0), fmpq(1)


def main():
    out = {}
    assert all(check_inverse_identity(E8[i]) for i in range(8))
    # subalgebra generated by e1, e2 in O:
    k12 = cd_mul(E8[1], E8[2])
    out["e1_dot_e2"] = list(k12)
    # H' = span{e0, e1, e2, k12}: closed under products? verify exactly:
    span = [E8[0], E8[1], E8[2], k12]

    def in_span(x):
        r = rank(mat([list(v) for v in span] + [list(x)]))
        return r == 4
    closed = all(in_span(cd_mul(a, b)) for a in span for b in span)
    out["Hprime_closed"] = bool(closed)

    # orthocomplement basis (Gram-Schmidt exact over Q):
    # vectors e3..e7 minus projections; with orthonormality exact via the
    # known CD structure: the complement of span{1, i, j, k} in the
    # doubling is span{l, il, jl, kl} = span{e4, e5, e6, e7}.
    complement = [E8[4], E8[5], E8[6], E8[7]]
    # verify exact orthogonality to span:
    def dot(a, b):
        return sum(x * y for x, y in zip(a, b))
    orth = all(dot(a, b) == 0 for a in span for b in complement)
    out["complement_orthogonal"] = bool(orth)

    # restrict L_1, L_i, L_j to blocks H' (coords 0..3 in basis order
    # (e0,e1,e2,k=e3? k12 IS e3?)):
    out["k12_is_e3"] = bool(k12 == E8[3])

    # block action: L_x restricted to H' has columns (x * h) for h in H';
    # if x in H', the product stays in H' (subalgebra) => block-diag:
    # L_x = B_x (+) B'_x in the (H', H'^perp) splitting, with cross terms
    def block_split(x):
        out_H = [cd_mul(x, h) for h in span]
        return all(in_span(o) for o in out_H)
    for xname, x in [("e1", E8[1]), ("e2", E8[2]), ("e4", E8[4])]:
        out[f"L_{xname}_preserves_Hprime"] = bool(block_split(x))

    # exact block counts:
    # B_x for x in H' on H' is the quaternion L_x; on the complement:
    # by CD doubling, for x in H' and c in complement: x*c lives in
    # complement and c*x also — the CROSS map H' x complement -> H'x comp
    # pairings. Verify entrywise-exactly:
    def full_matrix_blockcheck(x):
        L = L_of(x)
        bad = []
        for cc in range(8):
            for b in range(8):
                v = E8[b]
                prod = cd_mul(x, v)
                vec = [prod[i] for i in range(8)]
                vinH = in_span(vec)
                # which block does the INPUT b live in:
                b_in_H = b < 4 if k12 == E8[3] else None
                if k12 == E8[3]:
                    b_in_H = b in (0, 1, 2, 3)
                else:
                    # find index
                    b_in_H = any(vec_equal(v, s) for s in span)
                # L x (input in H) should output in H for x in H:
                if x in span or x in complement:
                    target_in_H = x in span
                    if b_in_H != target_in_H:
                        pass
                # record whether L[int][b] (column b) lives in span:
                bad.append((b, vinH))
        return bad
    # simpler exact check: for x in H' = {e0,e1,e2,e3} and b in H':
    # is column b of L_x inside span? For x = e4 (complement)?
    checkX = {}
    for xi, x in [("e0", E8[0]), ("e1", E8[1]), ("e2", E8[2]),
                  ("e4", E8[4]), ("e5", E8[5])]:
        cols_in_H = []
        for b in range(8):
            prod = cd_mul(x, E8[b])
            vec = list(prod)
            r4 = rank(mat([list(v) for v in span] + [vec]))
            cols_in_H.append(r4 == 4)
        checkX[xi] = cols_in_H
    out["columns_in_Hprime_by_x"] = checkX
    print(json.dumps(out, indent=1))
    sys.exit(0)


def vec_equal(a, b):
    return all(x == y for x, y in zip(a, b))


if __name__ == "__main__":
    main()
